import * as nodePath from 'node:path';
import * as fs from 'node:fs';
import * as crypto from 'node:crypto';
import * as os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import type { Command } from 'commander';
import { ParsePool } from './parse-pool.js';
// import { ResolveWorker } from './resolve-pool.js';
import chalk from 'chalk';
import { IxClient } from '../../client/api.js';
import type { GraphPatchPayload } from '../../client/types.js';
import { getEndpoint, resolveWorkspaceRoot } from '../config.js';
import { resolveGitHubToken } from '../github/auth.js';
import { parseGitHubRepo, fetchGitHubData } from '../github/fetch.js';
import { loadIngestionModules } from './ingestion-loader.js';
import {
  deterministicId,
  transformIssue,
  transformIssueComment,
  transformPR,
  transformPRComment,
  transformCommit,
} from '../github/transform.js';
// ---------------------------------------------------------------------------
// File discovery
// ---------------------------------------------------------------------------

// Inline extension set — mirrors core-ingestion/dist/languages.js EXT_MAP.
// Kept here so file discovery does NOT require loading tree-sitter grammars.
const SUPPORTED_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.py', '.java', '.c', '.h', '.cpp', '.cc', '.cxx', '.hpp',
  '.cs', '.go', '.rb', '.rs', '.php', '.kt', '.kts', '.swift',
  '.scala', '.sc',
  '.yaml', '.yml',
  '.dockerfile',
  '.sql',
  '.json',
  '.toml',
  '.md', '.markdown',
]);

export function isSupportedSourceFile(filePath: string): boolean {
  const fileName = nodePath.basename(filePath).toLowerCase();
  return fileName === 'dockerfile'
    || fileName.endsWith('.dockerfile')
    || SUPPORTED_EXTENSIONS.has(nodePath.extname(filePath).toLowerCase());
}

// ---------------------------------------------------------------------------
// Language filter helpers
// ---------------------------------------------------------------------------

/** Normalise user-supplied language names to their canonical enum values. */
const LANG_ALIASES: Record<string, string> = {
  'c++': 'cpp',
  'cplusplus': 'cpp',
  'c#': 'csharp',
  'cs': 'csharp',
  'js': 'javascript',
  'ts': 'typescript',
  'py': 'python',
  'rb': 'ruby',
  'rs': 'rust',
  'kt': 'kotlin',
};

function parseLangs(raw: string): Set<string> {
  return new Set(
    raw.split(',')
      .map(s => s.trim().toLowerCase())
      .map(s => LANG_ALIASES[s] ?? s)
      .filter(Boolean),
  );
}

const IGNORE_DIRS = new Set([
  'node_modules', '.git', '.hg', '.svn', 'dist', 'build', 'target', 'out', '.next',
  '__pycache__', '.tox', '.venv', 'venv', '.mypy_cache', '.pytest_cache',
  '.gradle', '.idea', '.vscode', '.settings', '.vs',
  '.cache', '.parcel-cache', 'coverage', '.nyc_output',
  'vendor', 'Pods', '.dart_tool', '.pub-cache',
  'bin', 'obj', 'pkg',
  '.ix', '.claude', '.gitnexus',
  'test', 'tests', '__tests__', 'spec', 'specs', 'e2e',
  'examples', 'fixtures', '__mocks__', '__fixtures__',
]);

// Generated file patterns — skipped by filename to avoid ingesting low-value autogenerated code.
// These files inflate parse time and graph size without contributing to architectural signal.
const GENERATED_FILE_SUFFIXES = [
  '.pb.go',        // protobuf generated Go
  '_deepcopy.go',  // controller-gen deepcopy (Kubernetes ecosystem)
  '_mock.go',      // gomock generated mocks
  '.pb.ts',        // protobuf generated TypeScript
  '.pb.js',        // protobuf generated JavaScript
  '_pb.ts',        // alternative protobuf TypeScript naming
  '_pb.js',        // alternative protobuf JavaScript naming
];

const GENERATED_FILE_PREFIXES = [
  'zz_generated',  // controller-gen convention (Kubernetes ecosystem)
  'mock_',         // gomock convention
];

function isGeneratedFile(basename: string): boolean {
  for (const suffix of GENERATED_FILE_SUFFIXES) {
    if (basename.endsWith(suffix)) return true;
  }
  for (const prefix of GENERATED_FILE_PREFIXES) {
    if (basename.startsWith(prefix)) return true;
  }
  return false;
}

const MAX_FILE_BYTES = 1024 * 1024; // 1 MB
const MINIFIED_BYTES_THRESHOLD = 200 * 1024;
const MINIFIED_MAX_LINE_THRESHOLD = 20_000;
const MINIFIED_AVG_LINE_THRESHOLD = 2_000;
const SLOW_WORK_LOG_MS = 5_000;
const SLOW_WORK_REPEAT_MS = 10_000;

function parsePositiveIntEnv(name: string, fallback: number): number {
  const raw = process.env[name];
  if (!raw) return fallback;
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function* walkFiles(
  dir: string,
  recursive: boolean,
): Generator<string> {
  let entries: fs.Dirent[];
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); }
  catch { return; }

  for (const entry of entries) {
    if (entry.isDirectory() && entry.name.startsWith('.') && entry.name !== '.') continue;
    if (IGNORE_DIRS.has(entry.name)) continue;
    const full = nodePath.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (recursive) yield* walkFiles(full, true);
    } else if (entry.isFile()) {
      if (isSupportedSourceFile(entry.name) && !isGeneratedFile(entry.name)) yield full;
    }
  }
}

function canonicalizeDiscoveredFilePath(filePath: string): string {
  try {
    return fs.realpathSync.native(filePath);
  } catch {
    return nodePath.resolve(filePath);
  }
}

export function dedupeDiscoveredFilePaths(
  filePaths: string[],
  canonicalize: (filePath: string) => string = canonicalizeDiscoveredFilePath,
): string[] {
  const deduped: string[] = [];
  const seenCanonical = new Set<string>();
  for (const filePath of filePaths) {
    const canonicalPath = canonicalize(filePath);
    if (seenCanonical.has(canonicalPath)) continue;
    seenCanonical.add(canonicalPath);
    deduped.push(canonicalPath);
  }
  return deduped;
}

function tryGitLsFiles(dir: string, recursive: boolean): string[] | null {
  try {
    const result = spawnSync(
      'git',
      ['ls-files', '--cached', '--others', '--exclude-standard'],
      {
        cwd: dir,
        encoding: 'utf-8',
        maxBuffer: 32 * 1024 * 1024,
      }
    );
    if (result.status !== 0) return null;

    const files: string[] = [];
    const seenCanonical = new Set<string>();
    for (const line of result.stdout.split(/\r?\n/)) {
      if (!line) continue;
      const fullPath = nodePath.resolve(dir, line);
      if (!recursive && nodePath.dirname(fullPath) !== dir) continue;
      if (!isSupportedSourceFile(fullPath)) continue;
      if (isGeneratedFile(nodePath.basename(fullPath))) continue;
      try {
        if (!fs.statSync(fullPath).isFile()) continue;
        const canonicalPath = canonicalizeDiscoveredFilePath(fullPath);
        if (seenCanonical.has(canonicalPath)) continue;
        seenCanonical.add(canonicalPath);
        files.push(canonicalPath);
      } catch {
        // Ignore racy deletes and permission issues during discovery.
      }
    }
    return files;
  } catch {
    return null;
  }
}

function sha256(content: Buffer): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

function isLikelyMinifiedSource(source: string): boolean {
  if (source.length < MINIFIED_BYTES_THRESHOLD) return false;

  let lineCount = 1;
  let currentLineLength = 0;
  let maxLineLength = 0;
  for (let i = 0; i < source.length; i++) {
    if (source.charCodeAt(i) === 10) {
      lineCount++;
      if (currentLineLength > maxLineLength) maxLineLength = currentLineLength;
      currentLineLength = 0;
    } else {
      currentLineLength++;
    }
  }
  if (currentLineLength > maxLineLength) maxLineLength = currentLineLength;

  const averageLineLength = source.length / Math.max(lineCount, 1);
  return maxLineLength >= MINIFIED_MAX_LINE_THRESHOLD || (lineCount <= 50 && averageLineLength >= MINIFIED_AVG_LINE_THRESHOLD);
}

function stripChunkOps(patch: GraphPatchPayload): GraphPatchPayload {
  return {
    ...patch,
    ops: patch.ops.filter(op => {
      if (op.type === 'UpsertNode' && op['kind'] === 'chunk') return false;
      if (op.type === 'UpsertEdge' && (op['predicate'] === 'CONTAINS_CHUNK' || op['predicate'] === 'NEXT')) return false;
      return true;
    }),
  };
}

/** Strip chunks and claims from patches — mapMode only needs nodes + edges. */
function stripMapModeOps(patch: GraphPatchPayload): GraphPatchPayload {
  return {
    ...patch,
    ops: patch.ops.filter(op => {
      if (op.type === 'AssertClaim' || op.type === 'RetractClaim') return false;
      if (op.type === 'UpsertNode' && op['kind'] === 'chunk') return false;
      if (op.type === 'UpsertEdge' && (op['predicate'] === 'CONTAINS_CHUNK' || op['predicate'] === 'NEXT')) return false;
      return true;
    }),
  };
}

const COMMIT_CONFLICT_RETRY_PATTERNS = [
  'write-write conflict',
  'timeout waiting to lock key',
  'error: 1200',
  // Transport-level failures (k8s ingress reset, socket drop under load).
  // Safe to retry because the server never received / committed the payload.
  'fetch failed',
  'econnreset',
  'econnrefused',
];

export function isRetryableCommitConflict(err: unknown): boolean {
  const message = String(err).toLowerCase();
  return COMMIT_CONFLICT_RETRY_PATTERNS.some(pattern => message.includes(pattern));
}

async function retryOnConflict<T>(fn: () => Promise<T>, maxRetries: number): Promise<T> {
  for (let attempt = 0; ; attempt++) {
    try {
      return await fn();
    } catch (err) {
      if (attempt >= maxRetries || !isRetryableCommitConflict(err)) throw err;
      // ArangoDB lock conflicts usually clear as soon as the competing transaction
      // commits. Transport errors may need a bit more breathing room under k8s load.
      const delay = 10 * (1 << attempt) + Math.random() * 10;
      await new Promise<void>(r => setTimeout(r, delay));
    }
  }
}

// ---------------------------------------------------------------------------
// Mtime cache — skip readFileSync+sha256 for unchanged files
// ---------------------------------------------------------------------------

interface MtimeCache {
  root: string;
  files: Record<string, number>; // absolute path → mtime (ms)
}

function mtimeCachePath(projectRoot: string): string {
  const key = crypto.createHash('sha256').update(projectRoot).digest('hex').slice(0, 12);
  return nodePath.join(os.homedir(), '.ix', `ingest_mtimes_${key}.json`);
}

function loadMtimeCache(projectRoot: string): Map<string, number> {
  try {
    const raw = fs.readFileSync(mtimeCachePath(projectRoot), 'utf-8');
    const data = JSON.parse(raw) as MtimeCache;
    if (data.root !== projectRoot) return new Map();
    return new Map(Object.entries(data.files));
  } catch {
    return new Map();
  }
}

function saveMtimeCache(projectRoot: string, mtimes: Map<string, number>): void {
  try {
    const dir = nodePath.join(os.homedir(), '.ix');
    fs.mkdirSync(dir, { recursive: true });
    const data: MtimeCache = { root: projectRoot, files: Object.fromEntries(mtimes) };
    fs.writeFileSync(mtimeCachePath(projectRoot), JSON.stringify(data));
  } catch {
    // Non-critical: ignore write errors
  }
}

// ---------------------------------------------------------------------------
// Progress bar
// ---------------------------------------------------------------------------

const PROG_BAR_WIDTH  = 25;
const PROG_LINE_WIDTH = 72;

function renderProgressLine(phase: string, current: number, total: number): string {
  if (total === 0) {
    return `  ${phase}...`.padEnd(PROG_LINE_WIDTH);
  }
  const pct    = Math.min(current / total, 1);
  const filled = Math.round(pct * PROG_BAR_WIDTH);
  const bar    = chalk.cyan('█'.repeat(filled)) + chalk.dim('░'.repeat(PROG_BAR_WIDTH - filled));
  const pctStr = `${Math.round(pct * 100)}%`.padStart(4);
  const w      = total.toString().length;
  const count  = `${current.toString().padStart(w)} / ${total}`;
  return `  ${phase.padEnd(8)}  ${bar}  ${pctStr}  ${count}`.padEnd(PROG_LINE_WIDTH);
}

// ---------------------------------------------------------------------------
// Command registration
// ---------------------------------------------------------------------------

export function registerIngestCommand(program: Command): void {
  program
    .command('ingest [path]')
    .description('Ingest source files or GitHub data into the knowledge graph')
    .option('--path <dir>', 'Path to ingest (alternative to positional argument)')
    .option('--no-recursive', 'Do not recurse into subdirectories (recursive is on by default)')
    .option('--github <owner/repo>', 'Ingest issues, PRs, and commits from a GitHub repository')
    .option('--token <pat>', 'GitHub personal access token')
    .option('--since <date>', 'Only fetch items updated after this date (ISO 8601)')
    .option('--limit <n>', 'Max items per category (default 50)', '50')
    .option('--force', 'Force re-ingest even if files are unchanged (useful after parser upgrades)')
    .option('--format <fmt>', 'Output format (text|json)', 'text')
    .option('--root <dir>', 'Workspace root directory')
    .option('--debug', 'Show phase timing breakdown', false)
    .option('--lang <langs>', 'Comma-separated languages to include (e.g. cpp,c or typescript). Aliases: c++=cpp, c#=csharp, py=python, ts=typescript, js=javascript')
    .addHelpText('after', '\nExamples:\n  ix ingest ./src\n  ix ingest --path ./src --force\n  ix ingest --path ./rocksdb --lang cpp,c\n  ix ingest --github owner/repo\n  ix ingest --github owner/repo --since 2026-01-01 --limit 20 --format json\n  ix ingest --github owner/repo --token ghp_xxxx')
    .action(async (positionalPath: string | undefined, opts: {
      path?: string; recursive?: boolean; force?: boolean; github?: string; token?: string;
      since?: string; limit: string; format: string; root?: string; debug?: boolean; lang?: string;
    }) => {
      const effectivePath = positionalPath ?? opts.path;
      if (opts.github) {
        await ingestGitHub(opts);
      } else if (effectivePath) {
        await ingestFiles(effectivePath, opts);
      } else {
        console.error('Error: provide a <path> or use --github <owner/repo>');
        process.exit(1);
      }
    });
}

// ---------------------------------------------------------------------------
// File ingestion — parse locally, send via /v1/patch
// ---------------------------------------------------------------------------

export async function ingestFiles(
  path: string,
  opts: { recursive?: boolean; force?: boolean; format: string; root?: string; debug?: boolean; printSummary?: boolean; suppressOutput?: boolean; lang?: string; mapMode?: boolean }
): Promise<void> {
  const debug = opts.debug || process.env.IX_DEBUG === '1';
  const mapMode = opts.mapMode === true;
  const trueStart = performance.now();

  const [{ parseFile, resolveEdges, isGrammarSupported }, { buildPatchWithResolution }, { languageFromPath }] = await loadIngestionModules();
  const moduleLoadMs = Math.round(performance.now() - trueStart);


  const resolvedPath = nodePath.isAbsolute(path)
    ? path
    : nodePath.resolve(resolveWorkspaceRoot(opts.root), path);

  // Workspace identity for client-agnostic backend.
  //
  // The backend used to dereference provenance.source_uri against the host
  // filesystem (via a broad HOME bind mount). We now emit workspace-relative
  // paths as the canonical source_uri, and pass a workspace_id derived from
  // the workspace root's absolute path. The backend treats both as opaque
  // strings; it never reads host files.
  const workspaceRoot = fs.statSync(resolvedPath).isDirectory()
    ? resolvedPath
    : nodePath.dirname(resolvedPath);
  const workspaceId = crypto.createHash('sha256').update(workspaceRoot).digest('hex');
  const toWorkspaceRelative = (absPath: string): string => {
    // Force workspace-local POSIX separators so IDs are stable across OS.
    const rel = nodePath.relative(workspaceRoot, absPath);
    return rel.split(nodePath.sep).join('/');
  };

  const client = new IxClient(getEndpoint());

  // Schema-version check forces a clean re-ingest when the backend's graph
  // format has changed in a way that invalidates existing node IDs (e.g. the
  // absolute→relative source_uri migration).
  const CLIENT_EXPECTED_SCHEMA_VERSION = 2;
  try {
    const health = await client.health();
    const serverVersion = (health as any)?.schema_version;
    if (typeof serverVersion === 'number' && serverVersion !== CLIENT_EXPECTED_SCHEMA_VERSION) {
      process.stderr.write(
        `\n  [schema mismatch] backend schema_version=${serverVersion}, ` +
        `client expects ${CLIENT_EXPECTED_SCHEMA_VERSION}. Forcing full re-ingest.\n`,
      );
      opts.force = true;
    }
  } catch (err) {
    if (debug) process.stderr.write(`\n  [schema check skipped] ${err}\n`);
  }

  const start = performance.now();

  // Worker pool for parallel file parsing across CPU cores
  const workerPath = nodePath.resolve(
    nodePath.dirname(fileURLToPath(import.meta.url)),
    '../../../../core-ingestion/dist/parse-worker.js',
  );
  let pool: ParsePool | null = null;
  const ensureParsePool = (): ParsePool => {
    if (pool) return pool;
    pool = new ParsePool(workerPath, Math.max(1, os.cpus().length - 1));
    pool.init();
    return pool;
  };


  let progressPhase   = 'Scanning';
  let progressCurrent = 0;
  let progressTotal   = 0;
  let progressStart   = performance.now();

  const interval = opts.format === 'text' ? setInterval(() => {
    if (debug && currentWorkLabel) {
      const workElapsed = performance.now() - currentWorkStart;
      if (workElapsed >= SLOW_WORK_LOG_MS && (lastSlowWorkNotice === 0 || workElapsed - lastSlowWorkNotice >= SLOW_WORK_REPEAT_MS)) {
        lastSlowWorkNotice = workElapsed;
        process.stderr.write(`\n  [slow ${progressPhase.toLowerCase()}] ${currentWorkLabel} (${Math.round(workElapsed / 1000)}s)\n`);
      }
    }
    process.stderr.write('\r' + renderProgressLine(progressPhase, progressCurrent, progressTotal));
  }, 80) : null;

  let filesDiscovered = 0;
  let filesChanged = 0;
  let patchesApplied = 0;
  let filesSkipped = 0;
  let parseErrors = 0;
  let tooLarge = 0;
  let minifiedLikely = 0;
  let latestRev = 0;
  let entitiesParsed = 0;
  let currentWorkLabel = '';
  let currentWorkStart = performance.now();
  let lastSlowWorkNotice = 0;

  const setCurrentWork = (label: string): void => {
    currentWorkLabel = label;
    currentWorkStart = performance.now();
    lastSlowWorkNotice = 0;
  };

  // Phase timing marks
  const timings = {
    moduleLoadMs: 0, discoverMs: 0, hashMs: 0, parseMs: 0,
    goIndexMs: 0,        // time to build Go global resolution index
    parseOnlyMs: 0,      // sum of just parseFile() call durations
    resolveMs: 0, buildPatchMs: 0, commitMs: 0,
    stripChunkOpsMs: 0,  // sum of stripChunkOps() durations (mapMode only)
    bulkCommitMs: 0,     // time in successful commitPatchBulk() calls
    fallbackCommitMs: 0, // time in per-file fallback commitPatch() calls
  };
  const resolveStats = {
    importLookups: 0, transitiveLookups: 0, globalFallbacks: 0,
    globalCandidateTotal: 0, resolvedImport: 0, resolvedTransitive: 0,
    resolvedGlobal: 0, resolvedQualifier: 0, skippedSameFile: 0, skippedAmbiguous: 0,
  };
  // Per-language parse timing: language → { ms, files }
  const langParseMs = new Map<string, { ms: number; files: number }>();
  // Total graph op counts across all committed batches
  let totalNodesEmitted = 0;
  let totalEdgesEmitted = 0;
  let totalClaimsEmitted = 0;

  const logSaveTiming = (
    files: number,
    resolveEdgesMs: number,
    buildPatchMs: number,
    stripMs: number,
    commitMs: number,
    totalSaveMs: number,
    nodes: number,
    edges: number,
    claims: number,
  ): void => {
    if (!debug) return;
    process.stderr.write(
      `\n[ingest-save] files=${files} resolveEdgesMs=${resolveEdgesMs} buildPatchMs=${buildPatchMs}` +
      (mapMode ? ` stripChunkOpsMs=${stripMs}` : '') +
      ` commitMs=${commitMs} totalSaveMs=${totalSaveMs} nodes=${nodes} edges=${edges} claims=${claims}\n`
    );
  };

  try {
    // Phase: discover files
    const langFilter = opts.lang ? parseLangs(opts.lang) : null;
    const supportsFile = (fileName: string): boolean => {
      if (!isGrammarSupported(fileName)) return false;
      if (!langFilter) return true;
      const lang = languageFromPath(fileName);
      return lang !== null && langFilter.has(lang);
    };

    if (!fs.existsSync(resolvedPath)) {
      throw new Error(`Path not found: ${resolvedPath}`);
    }
    const stat = fs.statSync(resolvedPath);
    const filePaths: string[] = dedupeDiscoveredFilePaths(
      stat.isFile()
        ? (isSupportedSourceFile(resolvedPath) ? [resolvedPath] : [])
        : (tryGitLsFiles(resolvedPath, opts.recursive ?? true) ?? Array.from(walkFiles(resolvedPath, opts.recursive ?? true))),
    );

    filesDiscovered = filePaths.length;
    const discovered = performance.now();
    timings.discoverMs = Math.round(discovered - start);

    progressPhase   = 'Parsing';
    progressTotal   = filePaths.length;
    progressCurrent = 0;
    progressStart   = performance.now();

    // Phase: mtime pre-filter — skip readFileSync+sha256 for files whose mtime
    // is unchanged since the last successful ingest (common "ix map" re-run case).
    const projectRoot = fs.statSync(resolvedPath).isDirectory() ? resolvedPath : nodePath.dirname(resolvedPath);
    const mtimeCache  = opts.force ? new Map<string, number>() : loadMtimeCache(projectRoot);
    const currentMtimes = new Map<string, number>();

    // DB-reset guard: if the mtime cache has entries but the server returns no hashes
    // for a small sample, the DB was wiped (e.g. `ix reset` run from a different dir
    // so the cache wasn't cleared). Invalidate the cache so files are re-ingested.
    if (!opts.force && mtimeCache.size > 0) {
      const samplePaths = [...mtimeCache.keys()].slice(0, 5);
      const sampleHashes = await loadExistingHashes(client, samplePaths, toWorkspaceRelative, debug);
      if (sampleHashes.size === 0) {
        mtimeCache.clear();
        if (debug) process.stderr.write(`\n  DB reset detected — invalidating mtime cache\n`);
      }
    }

    // Stat all files and partition into mtime-clean (skip) and mtime-changed (need hash check).
    const mtimeChangedPaths: string[] = [];
    for (const filePath of filePaths) {
      try {
        const st = fs.statSync(filePath);
        if (st.size === 0) { filesSkipped++; progressCurrent++; continue; }
        if (st.size > MAX_FILE_BYTES) { tooLarge++; progressCurrent++; continue; }
        const mtime = st.mtimeMs;
        currentMtimes.set(filePath, mtime);
        if (!opts.force && mtimeCache.get(filePath) === mtime) {
          filesSkipped++;
          progressCurrent++;   // mtime clean — assume unchanged
        } else {
          mtimeChangedPaths.push(filePath);
        }
      } catch (err) {
        parseErrors++;
        progressCurrent++;
        process.stderr.write(`\n  [stat error] ${filePath}: ${err}\n`);
      }
    }

    // Phase: hash lookup — only needed when mtime-changed files exist.
    let knownHashes: Map<string, string>;
    if (opts.force || mtimeChangedPaths.length > 0) {
      knownHashes = await loadExistingHashes(client, opts.force ? filePaths : mtimeChangedPaths, toWorkspaceRelative, debug);
      if (debug) process.stderr.write(`\n  Source hash lookup: ${knownHashes.size} known hashes (${mtimeChangedPaths.length} mtime-changed)\n`);
    } else {
      // All files are mtime-clean — skip server round-trip entirely.
      knownHashes = new Map();
      if (debug) process.stderr.write(`\n  All ${filePaths.length} files mtime-clean — skipping hash lookup\n`);
    }
    const hashed = performance.now();
    timings.hashMs = Math.round(hashed - discovered);

    // Phase: parse + commit — streaming to bound peak memory.
    //
    // Files are parsed in PARSE_STREAM_CHUNK-sized batches. After each batch,
    // resolveEdges runs on that batch and patches are committed before the next
    // batch is parsed. This keeps heap usage at O(chunk) instead of O(total).
    //
    // YIELD_EVERY yields the Node.js event loop so the progress bar timer can
    // fire even during the synchronous tree-sitter parse calls.
    //
    // Two paths:
    //   A) Has baseline or mtime-changed files → pre-scan first, skip module load
    //      entirely if nothing changed (common "ix map" re-run case).
    //   B) No baseline / force → load modules, parse + stream-commit all files.

    type ParsedFile = { filePath: string; parsed: any; hash: string; previousHash: string | undefined };
    let resolveEdgesFn: Function | null = null;
    let buildPatchFn: Function | null = null;
    let globalIndex: any = undefined;

    // Larger chunks for big repos: fewer resolve+commit cycles, better edge resolution per batch.
    // Smaller chunks pipeline better: resolve(N) overlaps with commit(N-1) + parse(N+1).
    // With 2000-file chunks, resolve takes 68s and dominates. With 500, resolve ~17s
    // and overlaps well with commit (~5s) + parse (~5s).
    const PARSE_STREAM_CHUNK     = filePaths.length > 10_000 ? 500 : 500;
    const COMMIT_HTTP_MAX_FILES  = parsePositiveIntEnv('IX_COMMIT_HTTP_MAX_FILES', 1000); // files per HTTP request to the backend
    const COMMIT_CONCURRENCY     = parsePositiveIntEnv('IX_COMMIT_CONCURRENCY', 8); // parallel HTTP save requests
    const COMMIT_CONFLICT_RETRIES = parsePositiveIntEnv('IX_COMMIT_CONFLICT_RETRIES', 6); // retry transient Arango lock conflicts
    const YIELD_EVERY            = 100;              // yield event loop every N files during parse

    if (debug) {
      process.stderr.write(
        `\n  Save config: httpBatch=${COMMIT_HTTP_MAX_FILES} concurrency=${COMMIT_CONCURRENCY}\n`
      );
    }

    const emptyEdges: any[] = [];

    type PreparedPatch = {
      patch: GraphPatchPayload;
      fileNumber: number;
      filePath: string;
    };

    const makePreparedPatch = (
      patch: GraphPatchPayload,
      fileNumber: number,
      filePath: string,
    ): PreparedPatch => ({ patch, fileNumber, filePath });

    // Commit HTTP batches in parallel (COMMIT_CONCURRENCY workers). Each worker pulls
    // the next unsent chunk from a shared queue. JS is single-threaded so the queue
    // index increment is atomic across await boundaries — no locking needed.
    const commitPreparedPatches = async (
      preparedPatches: PreparedPatch[],
      totalFiles: number,
      opts?: { updateProgress?: boolean },
    ): Promise<number> => {
      if (preparedPatches.length === 0) return 0;

      const chunks: PreparedPatch[][] = [];
      for (let i = 0; i < preparedPatches.length; i += COMMIT_HTTP_MAX_FILES) {
        chunks.push(preparedPatches.slice(i, i + COMMIT_HTTP_MAX_FILES));
      }

      const commitMsPerChunk = new Array<number>(chunks.length).fill(0);
      let nextChunk = 0;
      // Fallback mutex: serializes per-file commits across all workers so that
      // concurrent fallback loops don't race on revisions.current (Error 1200).
      let fallbackTail: Promise<void> = Promise.resolve();

      const runChunk = async (ci: number): Promise<void> => {
        const chunk = chunks[ci];
        const startFile = chunk[0].fileNumber;
        const endFile = chunk[chunk.length - 1].fileNumber;
        const endingPath = nodePath.basename(chunk[chunk.length - 1].filePath);
        const patches = chunk.map(item => item.patch);

        try {
          setCurrentWork(`commit ${startFile}-${endFile} of ${totalFiles} ending ${endingPath}`);
          const commitStart = performance.now();
          const result = await retryOnConflict(() => client.commitPatchBulk(patches), COMMIT_CONFLICT_RETRIES);
          const chunkMs = Math.round(performance.now() - commitStart);
          commitMsPerChunk[ci] = chunkMs;
          timings.bulkCommitMs += chunkMs;
          if (result.rev > latestRev) latestRev = result.rev;
          patchesApplied += patches.length;
        } catch (err) {
          if (debug) {
            process.stderr.write(
              `\n  [bulk failed, falling back to per-file] files ${startFile}-${endFile} (${patches.length} patches): ${err}\n`
            );
          }
          // Chain this chunk's fallback work onto the shared tail so that only one
          // fallback loop runs at a time. This prevents concurrent commitPatch
          // transactions from racing on revisions.current (write-write conflict).
          const prev = fallbackTail;
          let resolveThis!: () => void;
          fallbackTail = new Promise<void>(r => { resolveThis = r; });
          await prev;
          try {
            for (const item of chunk) {
              try {
                const commitStart = performance.now();
                const result = await retryOnConflict(() => client.commitPatch(item.patch), COMMIT_CONFLICT_RETRIES);
                const chunkMs = Math.round(performance.now() - commitStart);
                commitMsPerChunk[ci] += chunkMs;
                timings.fallbackCommitMs += chunkMs;
                if (result.rev > latestRev) latestRev = result.rev;
                patchesApplied++;
              } catch (commitErr) {
                parseErrors++;
                if (debug) {
                  const errMsg = String(commitErr);
                  const truncated = errMsg.length > 200 ? errMsg.slice(0, 200) + '…' : errMsg;
                  process.stderr.write(`\n  [commit error] ${item.patch.source?.uri}: ${truncated}\n`);
                }
              }
            }
          } finally {
            resolveThis();
          }
        }

        if (opts?.updateProgress) {
          progressCurrent = Math.max(progressCurrent, endFile);
        }
      };

      const worker = async (): Promise<void> => {
        while (true) {
          const ci = nextChunk++;
          if (ci >= chunks.length) break;
          await runChunk(ci);
        }
      };

      await Promise.all(
        Array.from({ length: Math.min(COMMIT_CONCURRENCY, chunks.length) }, () => worker())
      );

      return commitMsPerChunk.reduce((a, b) => a + b, 0);
    };

    /** Resolve edges within a batch, build patches, and commit in sub-chunks. */
    const flushBatch = async (batch: ParsedFile[]): Promise<void> => {
      if (batch.length === 0) return;
      filesChanged += batch.length;
      const saveStart = performance.now();
      let resolveEdgesMs = 0;
      let buildPatchMs = 0;
      let localStripMs = 0;
      let commitMs = 0;
      let batchNodes = 0;
      let batchEdges = 0;
      let batchClaims = 0;
      progressPhase = 'Saving';
      try {
        setCurrentWork(`resolve+commit batch ending ${nodePath.basename(batch[batch.length - 1].filePath)}`);

        const resolveStart = performance.now();
        const resolvedEdges = resolveEdgesFn!(batch.map(f => f.parsed), resolveStats, globalIndex);
        resolveEdgesMs = Math.round(performance.now() - resolveStart);
        const batchEdgesByFile = new Map<string, any[]>();
        for (const edge of resolvedEdges) {
          let arr = batchEdgesByFile.get(edge.srcFilePath);
          if (!arr) { arr = []; batchEdgesByFile.set(edge.srcFilePath, arr); }
          arr.push(edge);
        }

        setCurrentWork(`build commit payloads ending ${nodePath.basename(batch[batch.length - 1].filePath)}`);
        const buildStart = performance.now();
        const preparedPatches: PreparedPatch[] = [];
        for (let j = 0; j < batch.length; j++) {
          const { parsed: p, hash, previousHash } = batch[j];
          try {
            let patch = buildPatchFn!(p, hash, batchEdgesByFile.get(p.filePath) ?? emptyEdges, previousHash);
            if (mapMode) patch = stripMapModeOps(patch);
            // Tag every patch with the workspace_id. The backend stores this
            // as an opaque attribute. The source.uri has already been set to
            // the workspace-relative path upstream in buildPatch (because we
            // passed the relative path to parseFile).
            if (patch?.source) patch.source.workspaceId = workspaceId;
            preparedPatches.push(makePreparedPatch(patch, j + 1, p.filePath));
          } catch (err) {
            parseErrors++;
            process.stderr.write(`\n  [patch build error] ${p.filePath}: ${err}\n`);
          }
        }
        buildPatchMs += Math.round(performance.now() - buildStart);
        for (const pp of preparedPatches) {
          for (const op of pp.patch.ops) {
            if (op.type === 'UpsertNode') batchNodes++;
            else if (op.type === 'UpsertEdge') batchEdges++;
            else if (op.type === 'AssertClaim') batchClaims++;
          }
        }
        if (preparedPatches.length === 0) return;
        commitMs += await commitPreparedPatches(preparedPatches, batch.length);
      } finally {
        const totalSaveMs = Math.round(performance.now() - saveStart);
        timings.resolveMs += resolveEdgesMs;
        timings.buildPatchMs += buildPatchMs;
        timings.stripChunkOpsMs += localStripMs;
        timings.commitMs += commitMs;
        totalNodesEmitted += batchNodes;
        totalEdgesEmitted += batchEdges;
        totalClaimsEmitted += batchClaims;
        logSaveTiming(batch.length, resolveEdgesMs, buildPatchMs, localStripMs, commitMs, totalSaveMs, batchNodes, batchEdges, batchClaims);
        progressPhase = 'Parsing';
        progressStart = performance.now();
      }
    };

    /** Parse-all-first commit: resolve edges over full set, then commit in HTTP-sized batches. */
    const flushAll = async (allParsed: ParsedFile[]): Promise<void> => {
      if (allParsed.length === 0) return;
      filesChanged += allParsed.length;
      const previousPhase = progressPhase;
      const saveStart = performance.now();
      let resolveEdgesMs = 0;
      let buildPatchMs = 0;
      let localStripMs = 0;
      let commitMs = 0;
      let batchNodes = 0;
      let batchEdges = 0;
      let batchClaims = 0;
      progressPhase   = 'Saving';
      progressTotal   = allParsed.length;
      progressCurrent = 0;
      try {
        setCurrentWork(`resolve ${allParsed.length} files`);
        const resolveStart = performance.now();
        const resolvedEdges = resolveEdgesFn!(allParsed.map(f => f.parsed), resolveStats, globalIndex);
        resolveEdgesMs = Math.round(performance.now() - resolveStart);
        const edgesByFile = new Map<string, any[]>();
        for (const edge of resolvedEdges) {
          let arr = edgesByFile.get(edge.srcFilePath);
          if (!arr) { arr = []; edgesByFile.set(edge.srcFilePath, arr); }
          arr.push(edge);
        }
        setCurrentWork(`build commit payloads ending ${nodePath.basename(allParsed[allParsed.length - 1].filePath)}`);
        const buildStart = performance.now();
        const preparedPatches: PreparedPatch[] = [];
        for (let j = 0; j < allParsed.length; j++) {
          const { parsed: p, hash, previousHash } = allParsed[j];
          try {
            let patch = buildPatchFn!(p, hash, edgesByFile.get(p.filePath) ?? emptyEdges, previousHash);
            if (mapMode) patch = stripMapModeOps(patch);
            // Tag with workspace_id (see flushBatch).
            if (patch?.source) patch.source.workspaceId = workspaceId;
            preparedPatches.push(makePreparedPatch(patch, j + 1, p.filePath));
          } catch (err) {
            parseErrors++;
            process.stderr.write(`\n  [patch build error] ${p.filePath}: ${err}\n`);
          }
        }
        buildPatchMs += Math.round(performance.now() - buildStart);
        for (const pp of preparedPatches) {
          for (const op of pp.patch.ops) {
            if (op.type === 'UpsertNode') batchNodes++;
            else if (op.type === 'UpsertEdge') batchEdges++;
            else if (op.type === 'AssertClaim') batchClaims++;
          }
        }
        if (preparedPatches.length === 0) {
          progressCurrent = allParsed.length;
          return;
        }
        commitMs += await commitPreparedPatches(preparedPatches, allParsed.length, { updateProgress: true });
      } finally {
        const totalSaveMs = Math.round(performance.now() - saveStart);
        timings.resolveMs += resolveEdgesMs;
        timings.buildPatchMs += buildPatchMs;
        timings.stripChunkOpsMs += localStripMs;
        timings.commitMs += commitMs;
        totalNodesEmitted += batchNodes;
        totalEdgesEmitted += batchEdges;
        totalClaimsEmitted += batchClaims;
        logSaveTiming(allParsed.length, resolveEdgesMs, buildPatchMs, localStripMs, commitMs, totalSaveMs, batchNodes, batchEdges, batchClaims);
        progressPhase   = previousPhase;
        progressStart   = performance.now();
      }
    };

    if ((knownHashes.size > 0 || mtimeChangedPaths.length === 0) && !opts.force) {
      // Path A: has baseline or all mtime-clean → pre-scan to detect changes before loading modules.
      // If nothing changed, module load is skipped entirely.
      const changedPaths: Array<{ filePath: string; bytes: Buffer; hash: string; previousHash: string | undefined }> = [];
      for (const filePath of mtimeChangedPaths) {
        try {
          const bytes = fs.readFileSync(filePath);
          const hash = sha256(bytes);
          if (knownHashes.get(filePath) === hash) { filesSkipped++; progressCurrent++; continue; }
          const previousHash = knownHashes.get(filePath);
          changedPaths.push({ filePath, bytes, hash, previousHash: previousHash !== hash ? previousHash : undefined });
        } catch (err) {
          parseErrors++;
          progressCurrent++;
          process.stderr.write(`\n  [read error] ${filePath}: ${err}\n`);
        }
      }

      if (changedPaths.length > 0) {
        const moduleStart = performance.now();
        const [ingestion, patchBuilder] = await loadIngestionModules();
        timings.moduleLoadMs = Math.round(performance.now() - moduleStart);
        resolveEdgesFn = ingestion.resolveEdges as Function;
        buildPatchFn = patchBuilder.buildPatchWithResolution as Function;

        // Pre-filter minified files (main thread) then parse in parallel via worker pool.
        // filePath here is the workspace-relative path (what goes to parseFile
        // and downstream into buildPatch → source_uri). absFilePath is the
        // absolute path retained for any on-disk ops (reads already happened).
        const parseable: Array<{ filePath: string; absFilePath: string; source: string; hash: string; previousHash: string | undefined }> = [];
        for (const { filePath, bytes, hash, previousHash } of changedPaths) {
          const sourceText = bytes.toString('utf-8');
          if (isLikelyMinifiedSource(sourceText)) {
            minifiedLikely++;
            filesSkipped++;
            progressCurrent++;
            if (debug) process.stderr.write(`\n  [skip minified-likely] ${filePath}\n`);
            continue;
          }
          // parseFile receives the workspace-relative path so every
          // deterministic ID derived in buildPatch (node/edge/chunk/patch)
          // hashes relative paths. This makes graph IDs portable across
          // machines and removes backend dependence on host paths.
          parseable.push({ filePath: toWorkspaceRelative(filePath), absFilePath: filePath, source: sourceText, hash, previousHash });
        }

        progressPhase   = 'Parsing';
        progressTotal   = parseable.length;
        progressCurrent = 0;

        // Build global resolution index from all repo file paths (not just changed files)
        // so cross-batch imports resolve correctly even in streaming per-chunk mode.
        // Reuse bytes already read into changedPaths (on first install = all files, zero extra reads).
        // Only async-read Go files that were mtime-clean and therefore not in changedPaths.
        {
          const sources = new Map<string, string>();
          const changedSet = new Set(changedPaths.map(c => c.filePath));
          for (const { filePath, bytes } of changedPaths) {
            if (nodePath.extname(filePath) === '.go') sources.set(filePath, bytes.toString('utf-8'));
          }
          const remainingGoFiles = filePaths.filter(fp => nodePath.extname(fp) === '.go' && !changedSet.has(fp));
          const GO_READ_CONCURRENCY = 2000;
          for (let i = 0; i < remainingGoFiles.length; i += GO_READ_CONCURRENCY) {
            const batch = remainingGoFiles.slice(i, i + GO_READ_CONCURRENCY);
            const texts = await Promise.all(batch.map(fp => fs.promises.readFile(fp, 'utf-8').catch(() => null)));
            for (let j = 0; j < batch.length; j++) {
              if (texts[j] != null) sources.set(batch[j], texts[j]!);
            }
          }
          // Global resolution index is keyed on workspace-relative paths so
          // that edge resolution matches the relative paths we pass into
          // parseFile.
          const relSources = new Map<string, string>();
          for (const [abs, text] of sources) relSources.set(toWorkspaceRelative(abs), text);
          const relFilePaths = filePaths.map(toWorkspaceRelative);
          globalIndex = (ingestion.buildGlobalResolutionIndex as Function)(relFilePaths, relSources);
          sources.clear();
          relSources.clear();
        }

        let pendingFlush: Promise<void> = Promise.resolve();
        for (let i = 0; i < parseable.length; i += PARSE_STREAM_CHUNK) {
          const chunk = parseable.slice(i, i + PARSE_STREAM_CHUNK);
          // parseFile receives the workspace-relative path (f.filePath), so
          // every deterministic ID in the resulting patch hashes relative
          // paths. f.absFilePath is retained only for debug/error display.
          const parseResults = await Promise.all(
            chunk.map(f =>
              ensureParsePool().parse(f.filePath, f.source).then(r => { progressCurrent++; return r; }),
            ),
          );
          const batch: ParsedFile[] = [];
          for (let j = 0; j < chunk.length; j++) {
            const parsed = parseResults[j] as any;
            if (!parsed) { filesSkipped++; continue; }
            entitiesParsed += parsed.entities.length;
            batch.push({ filePath: chunk[j].filePath, parsed, hash: chunk[j].hash, previousHash: chunk[j].previousHash });
          }
          await pendingFlush;
          pendingFlush = flushBatch(batch);
        }
        await pendingFlush;
      }
    } else {
      // Path B: no baseline (first ingest) or --force → load modules, then stream parse + commit.
      const moduleStart = performance.now();
      const [ingestion, patchBuilder] = await loadIngestionModules();
      timings.moduleLoadMs = Math.round(performance.now() - moduleStart);
      resolveEdgesFn = ingestion.resolveEdges as Function;
      buildPatchFn = patchBuilder.buildPatchWithResolution as Function;

      // Build global resolution index from all repo file paths before the parse loop
      // so cross-batch imports resolve correctly even in streaming per-chunk mode.
      // Read all Go files in parallel to maximize I/O throughput.
      // Index keys are workspace-relative to match the relative paths we pass
      // into parseFile below.
      {
        const goIndexStart = performance.now();
        const sources = new Map<string, string>();
        const goFiles = filePaths.filter(fp => nodePath.extname(fp) === '.go');
        const GO_READ_CONCURRENCY = 2000;
        for (let i = 0; i < goFiles.length; i += GO_READ_CONCURRENCY) {
          const batch = goFiles.slice(i, i + GO_READ_CONCURRENCY);
          const texts = await Promise.all(batch.map(fp => fs.promises.readFile(fp, 'utf-8').catch(() => null)));
          for (let j = 0; j < batch.length; j++) {
            if (texts[j] != null) sources.set(toWorkspaceRelative(batch[j]), texts[j]!);
          }
        }
        const relFilePaths = filePaths.map(toWorkspaceRelative);
        globalIndex = ingestion.buildGlobalResolutionIndex(relFilePaths, sources);
        sources.clear();
        timings.goIndexMs = Math.round(performance.now() - goIndexStart);
      }

      progressPhase   = 'Parsing';
      progressTotal   = filePaths.length;
      progressCurrent = 0;

      // Pipeline overlap: read files asynchronously and dispatch to parse pool
      // immediately so workers start processing while more files are still being read.
      // Commit previous chunk's results while parsing the next chunk.
      let pendingFlushB: Promise<void> = Promise.resolve();
      for (let i = 0; i < filePaths.length; i += PARSE_STREAM_CHUNK) {
        const chunk = filePaths.slice(i, i + PARSE_STREAM_CHUNK);
        type FileData = { filePath: string; source: string; hash: string; previousHash: string | undefined } | null;
        const fileData: FileData[] = new Array(chunk.length).fill(null);
        const parsePromises: Promise<unknown>[] = new Array(chunk.length).fill(Promise.resolve(null));

        // Read files asynchronously and dispatch to parse pool as each file completes.
        // This keeps workers busy while I/O is still in flight for other files.
        // fd.filePath is the workspace-relative path, which is what parseFile
        // and all downstream ID derivations see. absFilePath is kept only so
        // error messages still point at the file on disk.
        const readAndDispatch = chunk.map(async (absFilePath, idx) => {
          try {
            const st = await fs.promises.stat(absFilePath);
            if (st.size === 0) { filesSkipped++; return; }
            if (st.size > MAX_FILE_BYTES) { tooLarge++; return; }
            const bytes = await fs.promises.readFile(absFilePath);
            const hash = sha256(bytes);
            if (!opts.force && knownHashes.get(absFilePath) === hash) { filesSkipped++; return; }
            const previousHash = knownHashes.get(absFilePath);
            const sourceText = bytes.toString('utf-8');
            if (isLikelyMinifiedSource(sourceText)) {
              minifiedLikely++;
              filesSkipped++;
              if (debug) process.stderr.write(`\n  [skip minified-likely] ${absFilePath}\n`);
              return;
            }
            const relFilePath = toWorkspaceRelative(absFilePath);
            const fd: NonNullable<FileData> = { filePath: relFilePath, source: sourceText, hash, previousHash: previousHash !== hash ? previousHash : undefined };
            fileData[idx] = fd;
            parsePromises[idx] = ensureParsePool().parse(fd.filePath, fd.source).then(r => { progressCurrent++; return r; });
          } catch (err) {
            parseErrors++;
            process.stderr.write(`\n  [read error] ${absFilePath}: ${err}\n`);
          }
        });
        await Promise.all(readAndDispatch);
        const parseResults = await Promise.all(parsePromises);

        const batch: ParsedFile[] = [];
        for (let j = 0; j < fileData.length; j++) {
          const f = fileData[j];
          if (!f) continue;
          const parsed = parseResults[j] as any;
          if (!parsed) { filesSkipped++; continue; }
          entitiesParsed += parsed.entities.length;
          batch.push({ filePath: f.filePath, parsed, hash: f.hash, previousHash: f.previousHash });
        }
        await pendingFlushB;
        pendingFlushB = flushBatch(batch);
      }
      await pendingFlushB;
    }

    const parsed = performance.now();
    timings.parseMs = Math.round(parsed - hashed);
    // Clear the parse bar
    if (interval) process.stderr.write('\r' + ' '.repeat(PROG_LINE_WIDTH) + '\r');

    const committed = performance.now();

    // Persist mtime cache so next run can skip unchanged files quickly.
    // Only save when no parse errors (avoid poisoning cache on partial failures).
    if (!opts.force && parseErrors === 0 && currentMtimes.size > 0) {
      saveMtimeCache(projectRoot, currentMtimes);
    }
  } finally {
    if (pool) {
      await pool.destroy();
    }
    if (interval) {
      clearInterval(interval);
      if (progressTotal > 0) {
        process.stderr.write('\r' + renderProgressLine(progressPhase, progressTotal, progressTotal));
      }
      process.stderr.write('\r' + ' '.repeat(PROG_LINE_WIDTH) + '\r');
      const elapsedSec = ((performance.now() - start) / 1000).toFixed(1);
      process.stderr.write(chalk.dim(`  Ingested in ${elapsedSec}s\n`));
    }
  }

  const elapsed = ((performance.now() - start) / 1000).toFixed(2);

  if (opts.suppressOutput === true) {
    return;
  }

  if (opts.format === 'json') {
    console.log(JSON.stringify({
      filesProcessed: filesDiscovered,
      filesChanged,
      patchesApplied,
      filesSkipped,
      entitiesParsed,
      latestRev,
      skipReasons: { unchanged: filesSkipped, emptyFile: 0, parseError: parseErrors, tooLarge, minifiedLikely },
      elapsedSeconds: parseFloat(elapsed),
      timings: {
        ...timings,
        parseOnlyMs: Math.round(timings.parseOnlyMs),
        stripChunkOpsMs: Math.round(timings.stripChunkOpsMs),
      },
      emitted: { nodes: totalNodesEmitted, edges: totalEdgesEmitted, claims: totalClaimsEmitted },
      langParseMs: Object.fromEntries(
        [...langParseMs.entries()].map(([lang, s]) => [lang, { ms: Math.round(s.ms), files: s.files }])
      ),
      resolveStats,
    }, null, 2));
  } else if (opts.printSummary !== false) {
    console.log(chalk.bold('\nIngest summary'));
    console.log(`  processed:   ${patchesApplied} files (${elapsed}s)`);
    console.log(`  discovered:  ${filesDiscovered} files`);
    console.log(`  changed:     ${filesChanged} files`);
    if (filesSkipped > 0) console.log(`  ${chalk.dim('skipped unchanged:')} ${filesSkipped}`);
    if (parseErrors > 0) console.log(`  ${chalk.red('parse errors:')}      ${parseErrors}`);
    if (tooLarge > 0) console.log(`  ${chalk.dim('skipped too large:')} ${tooLarge}`);
    if (minifiedLikely > 0) console.log(`  ${chalk.dim('skipped minified:')} ${minifiedLikely}`);
    console.log(`  rev:         ${latestRev}`);

    if (patchesApplied === 0 && filesDiscovered === 0) {
      console.log(chalk.yellow('\n  Warning: No files found. Check the path and supported extensions.'));
    } else if (patchesApplied === 0 && filesDiscovered > 0) {
      console.log(chalk.dim('\n  All files unchanged since last ingest.'));
    }

    if (debug) {
      console.log(chalk.dim(`\n  Phase timings:`));
      console.log(chalk.dim(`    modules:     ${timings.moduleLoadMs}ms`));
      console.log(chalk.dim(`    discover:    ${timings.discoverMs}ms`));
      console.log(chalk.dim(`    hash:        ${timings.hashMs}ms`));
      console.log(chalk.dim(`    go index:    ${timings.goIndexMs}ms`));
      console.log(chalk.dim(`    parse total: ${timings.parseMs}ms`));
      console.log(chalk.dim(`    parse only:  ${Math.round(timings.parseOnlyMs)}ms`));
      console.log(chalk.dim(`    resolve:     ${timings.resolveMs}ms`));
      console.log(chalk.dim(`    build:       ${timings.buildPatchMs}ms`));
      if (mapMode) {
        console.log(chalk.dim(`    stripChunk:  ${Math.round(timings.stripChunkOpsMs)}ms`));
      }
      console.log(chalk.dim(`    commit:      ${timings.commitMs}ms`));
      console.log(chalk.dim(`      bulk:      ${timings.bulkCommitMs}ms`));
      console.log(chalk.dim(`      fallback:  ${timings.fallbackCommitMs}ms`));
      console.log(chalk.dim(`\n  Emitted ops:`));
      console.log(chalk.dim(`    nodes:  ${totalNodesEmitted}`));
      console.log(chalk.dim(`    edges:  ${totalEdgesEmitted}`));
      console.log(chalk.dim(`    claims: ${totalClaimsEmitted}`));
      if (langParseMs.size > 0) {
        console.log(chalk.dim(`\n  Per-language parse times:`));
        const sorted = [...langParseMs.entries()].sort((a, b) => b[1].ms - a[1].ms);
        for (const [lang, stat] of sorted) {
          console.log(chalk.dim(`    ${lang.padEnd(12)} ${Math.round(stat.ms)}ms (${stat.files} files)`));
        }
      }
      console.log(chalk.dim(`\n  Resolve stats:`));
      console.log(chalk.dim(`    import lookups:     ${resolveStats.importLookups}`));
      console.log(chalk.dim(`    transitive lookups: ${resolveStats.transitiveLookups}`));
      console.log(chalk.dim(`    global fallbacks:   ${resolveStats.globalFallbacks}`));
      console.log(chalk.dim(`    avg candidates:     ${resolveStats.globalFallbacks > 0 ? (resolveStats.globalCandidateTotal / resolveStats.globalFallbacks).toFixed(1) : '0'}`));
      console.log(chalk.dim(`    resolved import:    ${resolveStats.resolvedImport}`));
      console.log(chalk.dim(`    resolved transitive:${resolveStats.resolvedTransitive}`));
      console.log(chalk.dim(`    resolved global:    ${resolveStats.resolvedGlobal}`));
      console.log(chalk.dim(`    resolved qualifier: ${resolveStats.resolvedQualifier}`));
      console.log(chalk.dim(`    skipped same-file:  ${resolveStats.skippedSameFile}`));
      console.log(chalk.dim(`    skipped ambiguous:  ${resolveStats.skippedAmbiguous}`));
    }

    console.log();
  }
}

// ---------------------------------------------------------------------------
// Load existing hashes from the server for change detection
// ---------------------------------------------------------------------------

// The backend now stores workspace-relative source_uri values. The CLI still
// tracks files internally by absolute path (needed for fs reads), so this
// helper converts to relative before the wire call and maps the server's
// response back onto the caller's absolute keys.
async function loadExistingHashes(
  client: IxClient,
  filePaths: string[],
  toRelative: (absPath: string) => string,
  debug = false,
): Promise<Map<string, string>> {
  try {
    const relPaths: string[] = new Array(filePaths.length);
    const relToAbs = new Map<string, string>();
    for (let i = 0; i < filePaths.length; i++) {
      const abs = filePaths[i];
      const rel = toRelative(abs);
      relPaths[i] = rel;
      relToAbs.set(rel, abs);
    }
    const serverHashes = await client.getSourceHashes(relPaths);
    const out = new Map<string, string>();
    for (const [rel, hash] of serverHashes) {
      const abs = relToAbs.get(rel);
      if (abs !== undefined) out.set(abs, hash);
    }
    return out;
  } catch (err) {
    if (debug) process.stderr.write(`\n  [hash lookup failed] ${err}\n`);
    return new Map();
  }
}

// ---------------------------------------------------------------------------
// GitHub ingestion (unchanged)
// ---------------------------------------------------------------------------

async function ingestGitHub(opts: {
  github?: string; token?: string; since?: string;
  limit: string; format: string;
}): Promise<void> {
  const repo = parseGitHubRepo(opts.github!);
  const token = await resolveGitHubToken(opts.token);
  const client = new IxClient(getEndpoint());
  const limit = parseInt(opts.limit, 10);
  const start = performance.now();

  const since = opts.since ?? new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

  if (opts.format !== 'json') {
    process.stderr.write(`Fetching from ${repo.owner}/${repo.repo} (since ${since})...\n`);
  }

  const data = await fetchGitHubData(repo, token, { since, limit });

  const allOps: any[] = [];
  for (const issue of data.issues) allOps.push(...transformIssue(repo, issue));
  for (const [issueNum, comments] of data.issueComments) {
    for (const comment of comments) allOps.push(...transformIssueComment(repo, issueNum, comment));
  }
  for (const pr of data.pullRequests) allOps.push(...transformPR(repo, pr));
  for (const [prNum, comments] of data.prComments) {
    for (const comment of comments) allOps.push(...transformPRComment(repo, prNum, comment));
  }
  for (const commit of data.commits) allOps.push(...transformCommit(repo, commit));

  const patch: GraphPatchPayload = {
    patchId: deterministicId(`github://${repo.owner}/${repo.repo}:${since}:${Date.now()}`),
    actor: 'ix/github-ingest',
    timestamp: new Date().toISOString(),
    source: {
      uri: `github://${repo.owner}/${repo.repo}`,
      extractor: 'github-ingest/1.0',
      sourceType: 'comment',
    },
    baseRev: 0,
    ops: allOps,
    replaces: [],
    intent: `GitHub ingestion: ${repo.owner}/${repo.repo}`,
  };

  const result = await client.commitPatch(patch);
  const elapsed = ((performance.now() - start) / 1000).toFixed(2);

  if (opts.format === 'json') {
    console.log(JSON.stringify({
      source: `${repo.owner}/${repo.repo}`,
      issues: data.issues.length,
      pullRequests: data.pullRequests.length,
      commits: data.commits.length,
      totalOps: allOps.length,
      rev: result.rev,
      status: result.status,
      elapsedSeconds: parseFloat(elapsed),
    }, null, 2));
  } else {
    console.log(chalk.bold('\nGitHub ingest summary'));
    console.log(`  repo:            ${repo.owner}/${repo.repo}`);
    console.log(`  issues:          ${data.issues.length}`);
    console.log(`  pull requests:   ${data.pullRequests.length}`);
    console.log(`  commits:         ${data.commits.length}`);
    console.log(`  total ops:       ${allOps.length}`);
    console.log(`  rev:             ${result.rev}`);
    console.log(`  elapsed:         ${elapsed}s`);
    console.log();
  }
}
