# -----------------------------------------------------------------------
# Build a Windows installer (.exe) for obsidian-connector using Inno Setup
#
# Stages project files, generates an Inno Setup script, and compiles
# it into a setup executable.
#
# Usage:
#   .\scripts\build-windows-installer.ps1                # auto-detect version
#   .\scripts\build-windows-installer.ps1 -Version v0.3.0
#
# Requirements:
#   - Inno Setup 6+ (iscc.exe on PATH or default install location)
# -----------------------------------------------------------------------

param(
    [string]$Version = ""
)

$ErrorActionPreference = "Stop"

# -- Locate repo root and tools -------------------------------------------

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path

# Auto-detect version from pyproject.toml if not provided
if (-not $Version) {
    $toml = Get-Content (Join-Path $RepoRoot "pyproject.toml") -Raw
    if ($toml -match 'version\s*=\s*"([^"]+)"') {
        $Version = $Matches[1]
    } else {
        $Version = "0.0.0"
    }
}
# Strip leading 'v' if present (tags use v0.3.0, Inno Setup wants 0.3.0)
$CleanVersion = $Version -replace '^v', ''

Write-Host "Building Windows installer for obsidian-connector $CleanVersion"

# Find Inno Setup compiler
$ISCC = $null
$Candidates = @(
    "iscc.exe",
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles}\Inno Setup 6\ISCC.exe",
    "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
)
foreach ($candidate in $Candidates) {
    if (Test-Path $candidate -ErrorAction SilentlyContinue) {
        $ISCC = $candidate
        break
    }
    $found = Get-Command $candidate -ErrorAction SilentlyContinue
    if ($found) {
        $ISCC = $found.Source
        break
    }
}
if (-not $ISCC) {
    Write-Error "Inno Setup compiler (iscc.exe) not found. Install from https://jrsoftware.org/isdown.php"
    exit 1
}
Write-Host "Using Inno Setup: $ISCC"

# -- Stage files -----------------------------------------------------------

$DistDir = Join-Path $RepoRoot "dist"
$StagingDir = Join-Path $DistDir ".win-staging"

if (Test-Path $StagingDir) { Remove-Item -Recurse -Force $StagingDir }
New-Item -ItemType Directory -Path $StagingDir -Force | Out-Null

Write-Host "Staging project files..."

# Directories and patterns to exclude (mirrors create-dmg.sh)
$ExcludeDirs = @(
    '.venv', '.git', '.claude', '.claude-plugin', 'dist',
    '__pycache__', '*.egg-info', 'vault-context-drafts',
    'templates', 'tools', 'dev', 'hooks', '.github'
)
$ExcludeFiles = @(
    '*.pyc', '.DS_Store', 'firebase-debug.log',
    'AGENTS.md', 'Makefile', 'main.py', 'Install.command'
)

# Use robocopy for efficient file staging
$ExcludeDirArgs = $ExcludeDirs | ForEach-Object { "/XD"; $_ }
$ExcludeFileArgs = $ExcludeFiles | ForEach-Object { "/XF"; $_ }

$robocopyArgs = @($RepoRoot, $StagingDir) + @("/E", "/NFL", "/NDL", "/NJH", "/NJS", "/NP") + $ExcludeDirArgs + $ExcludeFileArgs
& robocopy @robocopyArgs | Out-Null
# robocopy exit codes 0-7 are success
if ($LASTEXITCODE -gt 7) {
    Write-Error "robocopy failed with exit code $LASTEXITCODE"
    exit 1
}

Write-Host "Staged to: $StagingDir"

# -- Generate Inno Setup script -------------------------------------------

$IssFile = Join-Path $DistDir "obsidian-connector.iss"
$OutputExe = "obsidian-connector-${CleanVersion}-setup"

Write-Host "Generating Inno Setup script..."

$IssContent = @"
; obsidian-connector Windows installer
; Auto-generated by build-windows-installer.ps1

[Setup]
AppId={{B7E3F2A1-8C4D-4F5E-9A6B-1D2E3F4A5B6C}
AppName=obsidian-connector
AppVersion=$CleanVersion
AppVerName=obsidian-connector $CleanVersion
AppPublisher=Mario Urquia
AppPublisherURL=https://github.com/mariourquia/obsidian-connector
AppSupportURL=https://github.com/mariourquia/obsidian-connector/issues
DefaultDirName={userappdata}\obsidian-connector
DefaultGroupName=obsidian-connector
DisableProgramGroupPage=yes
LicenseFile=$StagingDir\LICENSE
OutputDir=$DistDir
OutputBaseFilename=$OutputExe
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
WelcomeLabel2=This will install obsidian-connector $CleanVersion on your computer.%n%nobsidian-connector connects Claude to your Obsidian vault -- morning briefings, idea capture, evening reflections, and 35 MCP tools.%n%nRequirements: Python 3.11+, Obsidian, Claude Desktop.

[Components]
Name: "core"; Description: "Core installation (MCP server + CLI)"; Types: full compact custom; Flags: fixed
Name: "claude_config"; Description: "Auto-configure Claude Desktop"; Types: full compact custom; Flags: fixed
Name: "skills"; Description: "Install Claude Code skills (/morning, /evening, etc.)"; Types: full
Name: "schedule"; Description: "Daily scheduled briefing (8:00 AM)"; Types: full

[Files]
Source: "$StagingDir\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Run]
; Create venv, install package, configure Claude Desktop
Filename: "powershell.exe"; \
    Parameters: "-ExecutionPolicy Bypass -File ""{app}\scripts\Install.ps1"" -NonInteractive"; \
    StatusMsg: "Setting up Python environment and configuring Claude Desktop..."; \
    Flags: runhidden waituntilterminated

; Install skills if selected
Filename: "powershell.exe"; \
    Parameters: "-ExecutionPolicy Bypass -File ""{app}\scripts\Install.ps1"" -NonInteractive -InstallSkills"; \
    StatusMsg: "Installing Claude Code skills..."; \
    Components: skills; \
    Flags: runhidden waituntilterminated

; Install scheduled task if selected
Filename: "powershell.exe"; \
    Parameters: "-ExecutionPolicy Bypass -File ""{app}\scripts\Install.ps1"" -NonInteractive -InstallSchedule"; \
    StatusMsg: "Setting up daily scheduled briefing..."; \
    Components: schedule; \
    Flags: runhidden waituntilterminated

[UninstallRun]
; Remove scheduled task on uninstall
Filename: "schtasks.exe"; \
    Parameters: "/DELETE /TN obsidian-connector-morning /F"; \
    Flags: runhidden; RunOnceId: "RemoveScheduledTask"

[UninstallDelete]
Type: filesandordirs; Name: "{app}\.venv"
Type: filesandordirs; Name: "{app}\__pycache__"

[Code]
function InitializeSetup(): Boolean;
begin
  Result := True;
end;
"@

$IssContent | Out-File -FilePath $IssFile -Encoding UTF8

Write-Host "Generated: $IssFile"

# -- Compile installer -----------------------------------------------------

Write-Host "Compiling installer..."
& $ISCC $IssFile
if ($LASTEXITCODE -ne 0) {
    Write-Error "Inno Setup compilation failed"
    exit 1
}

$ExePath = Join-Path $DistDir "$OutputExe.exe"
if (Test-Path $ExePath) {
    $Size = [math]::Round((Get-Item $ExePath).Length / 1MB, 1)
    Write-Host ""
    Write-Host "Created: $ExePath"
    Write-Host "Size: ${Size} MB"
} else {
    Write-Error "Expected output not found: $ExePath"
    exit 1
}

# -- Cleanup ---------------------------------------------------------------

Remove-Item -Recurse -Force $StagingDir
Remove-Item -Force $IssFile

Write-Host ""
Write-Host "Windows installer build complete."
