import { describe, expect, it } from 'vitest';

import { classifyFileRole } from '../role-classifier.js';

describe('classifyFileRole', () => {
  it('production fallback — normal source file', () => {
    const result = classifyFileRole('src/auth.ts');
    expect(result.role).toBe('production');
    expect(result.role_confidence).toBe(0.5);
    expect(result.role_signals).toHaveLength(0);
  });

  it('test by path — __tests__ directory', () => {
    const result = classifyFileRole('src/__tests__/auth.test.ts');
    expect(result.role).toBe('test');
  });

  it('test by filename — .spec. pattern', () => {
    const result = classifyFileRole('AuthService.spec.ts');
    expect(result.role).toBe('test');
  });

  it('test by import — vitest import in source', () => {
    const source = `import { describe, it, expect } from 'vitest';\n\ndescribe('foo', () => {});`;
    const result = classifyFileRole('src/someFile.ts', source);
    expect(result.role).toBe('test');
  });

  it('fixture by path', () => {
    const result = classifyFileRole('test/fixtures/user.json');
    expect(result.role).toBe('fixture');
  });

  it('fixture by filename — mock pattern', () => {
    const result = classifyFileRole('src/auth.mock.ts');
    expect(result.role).toBe('fixture');
  });

  it('generated by source marker — // Code generated', () => {
    const source = `// Code generated by protoc. DO NOT EDIT.\n\nexport const foo = 1;`;
    const result = classifyFileRole('src/schema.ts', source);
    expect(result.role).toBe('generated');
  });

  it('generated by path — /generated/ directory', () => {
    const result = classifyFileRole('src/generated/schema.ts');
    expect(result.role).toBe('generated');
  });

  it('external by path — vendor directory', () => {
    const result = classifyFileRole('src/vendor/somelib/index.ts');
    expect(result.role).toBe('external');
  });

  it('tooling by filename — jest.config.ts', () => {
    const result = classifyFileRole('jest.config.ts');
    expect(result.role).toBe('tooling');
  });

  it('confidence >= 0.8 for test files', () => {
    const byPath = classifyFileRole('src/__tests__/foo.test.ts');
    expect(byPath.role_confidence).toBeGreaterThanOrEqual(0.8);

    const byFilename = classifyFileRole('Foo.spec.ts');
    expect(byFilename.role_confidence).toBeGreaterThanOrEqual(0.8);
  });

  it('signals array is non-empty for non-production classifications', () => {
    const test = classifyFileRole('src/__tests__/foo.test.ts');
    expect(test.role).not.toBe('production');
    expect(test.role_signals.length).toBeGreaterThan(0);

    const fixture = classifyFileRole('test/fixtures/data.json');
    expect(fixture.role).not.toBe('production');
    expect(fixture.role_signals.length).toBeGreaterThan(0);

    const generated = classifyFileRole('src/generated/types.ts');
    expect(generated.role).not.toBe('production');
    expect(generated.role_signals.length).toBeGreaterThan(0);

    const external = classifyFileRole('src/vendor/lib/index.ts');
    expect(external.role).not.toBe('production');
    expect(external.role_signals.length).toBeGreaterThan(0);

    const tooling = classifyFileRole('jest.config.ts');
    expect(tooling.role).not.toBe('production');
    expect(tooling.role_signals.length).toBeGreaterThan(0);
  });
});
