# obsidian_connector/creation_dashboards.py
"""Fenced markdown dashboard generators for the Creation Vault OS (Task 5).

Generates materialized Obsidian markdown dashboards from the Project entity,
git+PR repo classifier, explainable next-action engine, backlog, freshness audit,
and session lifecycle.

Every write goes through ``write_manager.atomic_write``.
Fully-generated dashboards (Dashboard.md, Projects.md, Next Actions.md,
Stale Context.md, Pending Decisions.md, Active Sessions.md) are wholly
regenerated each run (carry ``last_sync`` + banner).

Hybrid files with user prose (repo views, one-pagers) use ``service:`` fences
to preserve hand-written content across regeneration.

Read-only seam: this module reads backlog/freshness/session; it never appends
events or mutates backlog.  No clock — ``now_iso`` is passed in.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Callable

# ---------------------------------------------------------------------------
# Fence markers (HTML comment style, matching creation_backlog convention)
# ---------------------------------------------------------------------------

_FENCE_PATTERN = re.compile(
    r"<!--\s*service:([^:]+):begin\s*-->(.*?)<!--\s*service:\1:end\s*-->",
    re.DOTALL,
)

_GENERATED_BANNER = (
    "<!-- generated by creation_dashboards — manual edits below "
    "service: fences are preserved; edits above are overwritten on refresh -->"
)


# ---------------------------------------------------------------------------
# Shared pure helpers
# ---------------------------------------------------------------------------

def _fm(meta: dict) -> str:
    """Render a YAML frontmatter block from *meta*.

    Always includes ``last_sync`` (from ``meta["last_sync"]``).  The returned
    string includes the opening and closing ``---`` delimiters.
    """
    lines = ["---"]
    for key, val in meta.items():
        if isinstance(val, bool):
            lines.append(f"{key}: {str(val).lower()}")
        elif isinstance(val, (int, float)):
            lines.append(f"{key}: {val}")
        elif val is None:
            lines.append(f"{key}: null")
        elif isinstance(val, list):
            if not val:
                lines.append(f"{key}: []")
            else:
                lines.append(f"{key}:")
                for item in val:
                    lines.append(f"  - {item}")
        else:
            # strings — quote if they contain special chars
            s = str(val)
            if any(c in s for c in (':', '#', '[', ']', '{', '}', ',', '"', "'", '\n')):
                lines.append(f'{key}: "{s}"')
            else:
                lines.append(f"{key}: {s}")
    lines.append("---")
    return "\n".join(lines)


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    """Render a Markdown pipe table.

    Parameters
    ----------
    headers:
        Column header strings.
    rows:
        List of rows, each a list of cell values (converted to str).

    Returns
    -------
    str
        A Markdown table string (no trailing newline).
    """
    if not headers:
        return ""
    col_widths = [len(h) for h in headers]
    str_rows = [[str(cell) for cell in row] for row in rows]
    for row in str_rows:
        for i, cell in enumerate(row):
            if i < len(col_widths):
                col_widths[i] = max(col_widths[i], len(cell))

    def _pad(s: str, width: int) -> str:
        return s + " " * (width - len(s))

    header_line = "| " + " | ".join(_pad(h, col_widths[i]) for i, h in enumerate(headers)) + " |"
    sep_line = "| " + " | ".join("-" * col_widths[i] for i in range(len(headers))) + " |"
    data_lines = []
    for row in str_rows:
        # Pad row to number of headers
        padded = list(row) + [""] * (len(headers) - len(row))
        data_lines.append(
            "| " + " | ".join(_pad(padded[i], col_widths[i]) for i in range(len(headers))) + " |"
        )
    return "\n".join([header_line, sep_line] + data_lines)


def _fence(name: str, body: str, existing: str | None) -> str:
    """Return a ``service:<name>`` fenced block.

    If *existing* already contains a ``service:<name>`` fence, the content
    inside it is preserved (the *body* argument is ignored).  This lets
    callers always pass the freshly-computed body while respecting any
    hand-written content the user has placed inside the fence.

    Parameters
    ----------
    name:
        Fence name (without ``service:`` prefix and without ``:begin``/``:end``).
    body:
        Default body to use when no existing fence content is found.
    existing:
        Full text of the file as it exists on disk (or None for a new file).

    Returns
    -------
    str
        The fenced block string, including begin/end markers.
    """
    begin = f"<!-- service:{name}:begin -->"
    end = f"<!-- service:{name}:end -->"

    if existing:
        pattern = re.compile(
            r"<!--\s*service:" + re.escape(name) + r":begin\s*-->(.*?)<!--\s*service:" + re.escape(name) + r":end\s*-->",
            re.DOTALL,
        )
        match = pattern.search(existing)
        if match:
            preserved = match.group(1).strip("\n")
            return f"{begin}\n{preserved}\n{end}"

    # No existing fence — emit the provided body
    body_stripped = body.strip("\n")
    if body_stripped:
        return f"{begin}\n{body_stripped}\n{end}"
    return f"{begin}\n{end}"


def _state_badge(classification: str) -> str:
    """Return a short emoji-free badge string for a classification."""
    _BADGES: dict[str, str] = {
        "clean-and-ready": "[clean]",
        "ready-for-next-agent": "[ready]",
        "mid-implementation": "[wip]",
        "waiting-on-pr-review": "[pr-review]",
        "blocked-by-tests": "[tests-fail]",
        "blocked-by-decision": "[needs-decision]",
        "needs-sync": "[needs-sync]",
        "behind": "[behind]",
        "ahead": "[ahead]",
        "dormant": "[dormant]",
        "stale": "[stale]",
        "unknown": "[unknown]",
    }
    return _BADGES.get(classification, f"[{classification}]")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _project_dir(vault_path: Path, project_name: str) -> Path:
    return vault_path / "Projects" / project_name


def _safe_write(path: Path, content: str, vault_path: Path, dry_run: bool) -> str:
    """Write *content* to *path* via atomic_write unless dry_run."""
    from obsidian_connector.write_manager import atomic_write
    from obsidian_connector.audit import log_action

    rel = str(path.relative_to(vault_path))
    if dry_run:
        return rel
    path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write(path, content, vault_root=vault_path, tool_name="creation_dashboards")
    log_action("creation_dashboards", "write", rel)
    return rel


# ---------------------------------------------------------------------------
# generate_global_dashboard
# ---------------------------------------------------------------------------

def generate_global_dashboard(
    vault: "str | Path",
    *,
    now_iso: str,
    github_root: "str | Path | None" = None,
    dry_run: bool = False,
    runner: "Callable | None" = None,
) -> dict:
    """Generate ``Dashboard.md`` — the hybrid global triage console.

    Layout:
    1. ``## ▶ Do next`` — top 5 from ``next_actions(limit=5)``
    2. ``## Projects`` table — one row per project (state from repo_status)
    3. ``## Needs decision`` / ``## Stale`` / ``## Clean & ready`` rollups
    4. Links footer

    Returns ``{path, dry_run}``.
    """
    from obsidian_connector import creation_next as cn
    from obsidian_connector import creation_projects as cp
    from obsidian_connector import creation_repo_status as crs
    from obsidian_connector import creation_backlog as cb

    vault_path = Path(vault)
    gh_root = Path(github_root) if github_root else Path.home() / "dev"

    # --- top 5 next actions --------------------------------------------------
    runner_kwargs: dict = {}
    if runner is not None:
        runner_kwargs["runner"] = runner

    recs = cn.next_actions(
        vault_path,
        scope="global",
        github_root=gh_root,
        now_iso=now_iso,
        limit=5,
        **runner_kwargs,
    )

    do_next_lines: list[str] = []
    for rec in recs:
        proj = rec.get("project") or ""
        repo = rec.get("repo") or ""
        loc = " · ".join(x for x in [proj, repo] if x)
        reasons = rec.get("reason") or []
        reason_str = "; ".join(str(r) for r in reasons[:2])
        action = rec.get("action", "")
        flags = ""
        if rec.get("requires_mario_decision"):
            flags += " [needs-decision]"
        if rec.get("confidence", 1.0) < 0.3:
            flags += " [low-confidence]"
        line = f"- **{action}**{flags}"
        if loc:
            line += f" — {loc}"
        if reason_str:
            line += f"  _({reason_str})_"
        do_next_lines.append(line)

    if not do_next_lines:
        do_next_lines = ["_No actionable items found._"]

    # --- projects table ------------------------------------------------------
    projects = cp.list_projects(vault_path)

    table_rows: list[list[str]] = []
    needs_decision_names: list[str] = []
    stale_names: list[str] = []
    clean_names: list[str] = []

    for proj in projects:
        # Collect repo statuses for this project
        repo_entries = cp.project_repo_entries(vault_path, proj)
        statuses: list["crs.RepoStatus"] = []
        for entry in repo_entries:
            try:
                rs = crs.repo_status(
                    entry,
                    github_root=gh_root,
                    now_iso=now_iso,
                    with_prs=False,
                    with_tests=False,
                    with_build=False,
                    **runner_kwargs,
                )
                statuses.append(rs)
            except Exception:
                pass

        # Rollup classification: worst-case wins
        _PRIORITY_ORDER = [
            "needs-sync", "blocked-by-tests", "waiting-on-pr-review",
            "mid-implementation", "behind", "ahead", "blocked-by-decision",
            "stale", "dormant", "clean-and-ready", "ready-for-next-agent", "unknown",
        ]
        def _cls_rank(c: str) -> int:
            try:
                return _PRIORITY_ORDER.index(c)
            except ValueError:
                return len(_PRIORITY_ORDER)

        worst_cls = "unknown"
        worst_next = ""
        if statuses:
            worst = min(statuses, key=lambda r: _cls_rank(r.classification))
            worst_cls = worst.classification
            worst_next = worst.next_action or ""

        badge = _state_badge(worst_cls)

        # Flags: decision / stale
        all_backlog = cb.list_backlog(vault_path, project=proj.slug)
        has_decision = any(i.get("needs_decision") for i in all_backlog)
        n_stale = sum(1 for rs in statuses if rs.classification in ("stale", "dormant"))
        flag_parts: list[str] = []
        if has_decision:
            flag_parts.append("decision")
        if n_stale:
            flag_parts.append(f"{n_stale} stale")
        flags_str = ", ".join(flag_parts) if flag_parts else ""

        # Truncate next action
        next_str = (worst_next[:60] + "...") if len(worst_next) > 60 else worst_next

        # priority: from highest-priority backlog item
        priorities = [i.get("priority", "P3") for i in all_backlog]
        best_pri = min(priorities) if priorities else "—"

        table_rows.append([proj.name, best_pri, badge, str(len(proj.repos)), flags_str, next_str])

        # Rollup buckets
        if has_decision or worst_cls == "blocked-by-decision":
            needs_decision_names.append(proj.name)
        if worst_cls in ("stale", "dormant"):
            stale_names.append(proj.name)
        if worst_cls in ("clean-and-ready", "ready-for-next-agent"):
            clean_names.append(proj.name)

    projects_table = _table(
        ["Project", "Pri", "State", "Repos", "Flags", "Next action"],
        table_rows,
    )

    # --- rollup sections -----------------------------------------------------
    def _names_list(names: list[str]) -> str:
        if not names:
            return "_none_"
        return "\n".join(f"- [[Projects/{n}/Project Dashboard]]" for n in names)

    rollups = (
        f"## Needs decision\n\n{_names_list(needs_decision_names)}\n\n"
        f"## Stale\n\n{_names_list(stale_names)}\n\n"
        f"## Clean & ready\n\n{_names_list(clean_names)}"
    )

    # --- assemble -----------------------------------------------------------
    fm = _fm({
        "type": "creation-dashboard",
        "last_sync": now_iso,
        "generated_by": "creation_dashboards",
    })

    content = (
        f"{fm}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"# Creation Dashboard\n\n"
        f"_Last sync: {now_iso}_\n\n"
        f"## ▶ Do next\n\n"
        + "\n".join(do_next_lines)
        + f"\n\n## Projects\n\n{projects_table}\n\n"
        + rollups
        + "\n\n---\n\n"
        "**Links:** [[Projects]] · [[Next Actions]] · [[Stale Context]] · "
        "[[Pending Decisions]] · [[Active Sessions]]\n"
    )

    path = vault_path / "Dashboard.md"
    rel = _safe_write(path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run}


# ---------------------------------------------------------------------------
# generate_project_dashboard
# ---------------------------------------------------------------------------

def generate_project_dashboard(
    vault: "str | Path",
    project: "str",
    *,
    now_iso: str,
    github_root: "str | Path | None" = None,
    dry_run: bool = False,
    runner: "Callable | None" = None,
) -> dict:
    """Generate ``Projects/{Project}/Project Dashboard.md``.

    Layout:
    header (name + goal/intent) → Next lead → state badges → Repos table →
    Top backlog → Load for an agent → links.

    Returns ``{path, dry_run}``.
    """
    from obsidian_connector import creation_projects as cp
    from obsidian_connector import creation_repo_status as crs
    from obsidian_connector import creation_next as cn
    from obsidian_connector import creation_backlog as cb

    vault_path = Path(vault)
    gh_root = Path(github_root) if github_root else Path.home() / "dev"
    runner_kwargs: dict = {}
    if runner is not None:
        runner_kwargs["runner"] = runner

    proj_obj = cp.get_project(vault_path, project)
    if proj_obj is None:
        return {"path": None, "dry_run": dry_run, "error": f"project not found: {project}"}

    prose = cp.read_one_pager_prose(vault_path, proj_obj)
    goal = prose.get("goal") or prose.get("intent") or "_no one-pager yet_"

    # --- top next action for this project ------------------------------------
    recs = cn.next_actions(
        vault_path,
        scope="project",
        project=proj_obj.slug,
        github_root=gh_root,
        now_iso=now_iso,
        limit=3,
        **runner_kwargs,
    )

    if recs:
        top = recs[0]
        reasons = "; ".join(str(r) for r in (top.get("reason") or [])[:2])
        next_lead = f"**→ Next:** {top['action']}"
        if reasons:
            next_lead += f"  _({reasons})_"
    else:
        next_lead = "**→ Next:** _no actionable items_"

    # --- repo statuses -------------------------------------------------------
    repo_entries = cp.project_repo_entries(vault_path, proj_obj)
    repo_statuses: list["crs.RepoStatus"] = []
    for entry in repo_entries:
        try:
            rs = crs.repo_status(
                entry,
                github_root=gh_root,
                now_iso=now_iso,
                with_prs=False,
                with_tests=False,
                with_build=False,
                **runner_kwargs,
            )
            repo_statuses.append(rs)
        except Exception:
            pass

    # State badges summary
    n_decision = sum(1 for rs in repo_statuses if rs.classification == "blocked-by-decision")
    n_stale = sum(1 for rs in repo_statuses if rs.classification in ("stale", "dormant"))
    n_blocked = sum(1 for rs in repo_statuses if "blocked" in rs.classification)
    n_clean = sum(1 for rs in repo_statuses if rs.classification in ("clean-and-ready", "ready-for-next-agent"))

    badge_parts: list[str] = []
    if n_decision:
        badge_parts.append(f"{n_decision} needs-decision")
    if n_stale:
        badge_parts.append(f"{n_stale} stale")
    if n_blocked:
        badge_parts.append(f"{n_blocked} blocked")
    if n_clean:
        badge_parts.append(f"{n_clean} clean")
    badges_line = "  ".join(f"[{b}]" for b in badge_parts) if badge_parts else "[no repos]"

    # Repos table
    repo_table_rows: list[list[str]] = []
    for rs in repo_statuses:
        branch = rs.branch or "?"
        head = rs.head[:7] if rs.head else "?"
        badge = _state_badge(rs.classification)
        next_a = (rs.next_action[:50] + "...") if len(rs.next_action) > 50 else rs.next_action
        repo_table_rows.append([rs.display_name, f"{branch}@{head}", badge, next_a])

    repos_table = _table(["Repo", "Branch", "State", "Next"], repo_table_rows)

    # Top backlog
    backlog = cb.list_backlog(vault_path, project=proj_obj.slug)
    backlog_lines: list[str] = []
    for item in backlog[:10]:
        pri = item.get("priority", "?")
        status = item.get("status", "?")
        title = item.get("title", item["id"])
        bid = item["id"]
        flags = ""
        if item.get("needs_decision"):
            flags += " [needs-decision]"
        if status == "blocked":
            flags += " [blocked]"
        backlog_lines.append(f"- `{pri}` `{status}` {title}{flags}  `{bid}`")

    if not backlog_lines:
        backlog_lines = ["_No backlog items._"]

    # Load for an agent section
    one_pager_link = f"[[Projects/{proj_obj.name}/Project One-Pager]]"
    repo_links = "  ".join(
        f"[[Projects/{proj_obj.name}/Repos/{r}]]" for r in proj_obj.repos
    )
    agent_load = (
        f"One-pager: {one_pager_link}\n\n"
        f"Repo views: {repo_links}\n\n"
        "_Context pack: not yet generated._"
    )

    # --- assemble -----------------------------------------------------------
    fm = _fm({
        "type": "project-dashboard",
        "project": proj_obj.name,
        "last_sync": now_iso,
        "generated_by": "creation_dashboards",
    })

    n_repos = len(proj_obj.repos)
    content = (
        f"{fm}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"# {proj_obj.name}\n\n"
        f"_{goal}_\n\n"
        f"{next_lead}\n\n"
        f"{badges_line}\n\n"
        f"## Repos ({n_repos})\n\n"
        f"{repos_table}\n\n"
        f"## Top backlog (ranked)\n\n"
        + "\n".join(backlog_lines)
        + f"\n\n## Load for an agent\n\n{agent_load}\n\n"
        "---\n\n"
        f"**Links:** [[Dashboard]] · [[Projects]] · [[Projects/{proj_obj.name}/Project One-Pager]]\n"
    )

    path = _project_dir(vault_path, proj_obj.name) / "Project Dashboard.md"
    rel = _safe_write(path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run}


# ---------------------------------------------------------------------------
# generate_repo_view
# ---------------------------------------------------------------------------

def generate_repo_view(
    vault: "str | Path",
    project: "str",
    repo: "str",
    *,
    now_iso: str,
    github_root: "str | Path | None" = None,
    dry_run: bool = False,
    runner: "Callable | None" = None,
) -> dict:
    """Generate ``Projects/{Project}/Repos/{repo}.md``.

    Generated repo state lives inside a ``service:repo-status`` fence.
    User notes OUTSIDE the fence are preserved across regeneration.

    Returns ``{path, dry_run}``.
    """
    from obsidian_connector import creation_projects as cp
    from obsidian_connector import creation_repo_status as crs
    from obsidian_connector import creation_backlog as cb

    vault_path = Path(vault)
    gh_root = Path(github_root) if github_root else Path.home() / "dev"
    runner_kwargs: dict = {}
    if runner is not None:
        runner_kwargs["runner"] = runner

    proj_obj = cp.get_project(vault_path, project)
    if proj_obj is None:
        return {"path": None, "dry_run": dry_run, "error": f"project not found: {project}"}

    repo_entries = cp.project_repo_entries(vault_path, proj_obj)
    entry = next((e for e in repo_entries if e.dir_name == repo), None)
    if entry is None:
        return {"path": None, "dry_run": dry_run, "error": f"repo not found: {repo}"}

    try:
        rs = crs.repo_status(
            entry,
            github_root=gh_root,
            now_iso=now_iso,
            with_prs=True,
            with_tests=False,
            with_build=False,
            **runner_kwargs,
        )
    except Exception as exc:
        rs = None
        _rs_err = str(exc)

    # Read existing file (to preserve user notes outside the fence)
    repo_view_path = _project_dir(vault_path, proj_obj.name) / "Repos" / f"{repo}.md"
    existing: str | None = None
    if repo_view_path.exists():
        try:
            existing = repo_view_path.read_text(encoding="utf-8")
        except OSError:
            pass

    # Extract user notes that live OUTSIDE the service:repo-status fence
    user_notes = _extract_user_notes_outside_fence(existing, "repo-status")

    # Build the generated state body
    if rs is not None:
        classification = rs.classification
        badge = _state_badge(classification)

        git_lines = [
            f"- **Path:** `{rs.repo_path}`",
            f"- **Branch:** `{rs.branch}` @ `{rs.head}`",
            f"- **Dirty:** {rs.dirty}  **Untracked:** {rs.untracked}",
            f"- **vs origin:** {rs.ahead} ahead, {rs.behind} behind",
        ]
        if rs.recent_commits:
            git_lines.append("\n**Recent commits:**")
            for c in rs.recent_commits[:5]:
                git_lines.append(f"  - {c}")
        git_section = "\n".join(git_lines)

        # PRs section
        open_pr_lines: list[str] = []
        for pr in rs.open_prs:
            draft_flag = " [draft]" if pr.get("is_draft") else ""
            open_pr_lines.append(f"- #{pr.get('number', '?')} {pr.get('title', '')}{draft_flag}")
        if not open_pr_lines:
            open_pr_lines = ["_No open PRs._"]

        merged_pr_lines: list[str] = []
        for pr in rs.merged_prs_recent:
            merged_pr_lines.append(f"- #{pr.get('number', '?')} {pr.get('title', '')}")
        if not merged_pr_lines:
            merged_pr_lines = ["_No recently merged PRs._"]

        pr_section = (
            "**Open:**\n" + "\n".join(open_pr_lines)
            + "\n\n**Recently merged:**\n" + "\n".join(merged_pr_lines)
        )

        # Tests / build / deploy
        t_status = rs.tests.get("status", "unknown")
        t_summary = rs.tests.get("summary", "")
        b_status = rs.build.get("status", "unknown")
        d_status = rs.deploy.get("status", "unknown")
        tbd_section = (
            f"- **Tests:** {t_status}"
            + (f" — `{t_summary[:120]}`" if t_summary else "")
            + f"\n- **Build:** {b_status}"
            + f"\n- **Deploy:** {d_status}"
        )

        # Work context
        repo_backlog = cb.list_backlog(vault_path, project=proj_obj.slug)
        repo_items = [i for i in repo_backlog if repo in (i.get("repos") or [])]
        backlog_links: list[str] = []
        for item in repo_items[:5]:
            bid = item["id"]
            title = item.get("title", bid)
            backlog_links.append(f"- [[Backlog/{proj_obj.slug}/{bid}]] — {title}")

        blockers = list(rs.blockers)
        blocker_lines = [f"- {b}" for b in blockers] if blockers else ["_none_"]

        context_section = (
            f"**Blockers:**\n" + "\n".join(blocker_lines)
            + f"\n\n**Linked backlog:**\n"
            + ("\n".join(backlog_links) if backlog_links else "_none_")
            + f"\n\n**Suggested workflow:** _none configured_"
        )

        generated_body = (
            f"{badge}  **{classification}**\n\n"
            f"_Last sync: {now_iso}_\n\n"
            f"## Git\n\n{git_section}\n\n"
            f"## PRs\n\n{pr_section}\n\n"
            f"## Tests / build / deploy\n\n{tbd_section}\n\n"
            f"## Work context\n\n{context_section}"
        )
    else:
        generated_body = (
            f"[unknown]  **repo state unavailable**\n\n"
            f"_Last sync: {now_iso}_\n\n"
            f"_Error: {_rs_err}_"
        )

    # The fence wraps the generated region; user notes come after
    fence_block = _fence("repo-status", generated_body, existing)

    fm = _fm({
        "type": "repo-view",
        "project": proj_obj.name,
        "repo": repo,
        "last_sync": now_iso,
        "generated_by": "creation_dashboards",
    })

    # Preserve user notes that were originally outside (after) the fence
    user_section = ""
    if user_notes.strip():
        user_section = f"\n\n{user_notes.strip()}"

    content = (
        f"{fm}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"# {entry.display_name}\n\n"
        f"{fence_block}"
        f"{user_section}\n"
    )

    rel = _safe_write(repo_view_path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run}


def _extract_user_notes_outside_fence(existing: str | None, fence_name: str) -> str:
    """Return text that lives AFTER the service fence (user notes region).

    Strips any content that was generated by this module (frontmatter,
    banner, heading, the fence block itself) and returns only the trailing
    user-authored text.
    """
    if not existing:
        return ""
    begin_marker = f"<!-- service:{fence_name}:begin -->"
    end_marker = f"<!-- service:{fence_name}:end -->"
    b = existing.find(begin_marker)
    e = existing.find(end_marker)
    if b == -1 or e == -1:
        return ""
    after_fence = existing[e + len(end_marker):].strip()
    return after_fence


# ---------------------------------------------------------------------------
# generate_project_one_pager
# ---------------------------------------------------------------------------

def generate_project_one_pager(
    vault: "str | Path",
    project: "str",
    *,
    now_iso: str,
    dry_run: bool = False,
) -> dict:
    """Scaffold ``Projects/{Project}/Project One-Pager.md`` with prose fences.

    ONLY creates the file when absent.  Never overwrites existing prose.

    Returns ``{path, dry_run, created}`` where ``created`` is False when the
    file already existed and was left untouched.
    """
    from obsidian_connector import creation_projects as cp

    vault_path = Path(vault)
    proj_obj = cp.get_project(vault_path, project)
    if proj_obj is None:
        return {"path": None, "dry_run": dry_run, "error": f"project not found: {project}"}

    path = _project_dir(vault_path, proj_obj.name) / "Project One-Pager.md"

    if path.exists():
        rel = str(path.relative_to(vault_path))
        return {"path": rel, "dry_run": dry_run, "created": False}

    fm = _fm({
        "type": "project-one-pager",
        "project": proj_obj.name,
        "created_at": now_iso,
    })

    def _prose_fence(field: str, placeholder: str) -> str:
        return _fence(f"one-pager-{field}", placeholder, None)

    content = (
        f"{fm}\n\n"
        f"# {proj_obj.name} — One-Pager\n\n"
        f"## Goal\n\n{_prose_fence('goal', '_Describe the project goal in one sentence._')}\n\n"
        f"## Intent\n\n{_prose_fence('intent', '_What does success look like?_')}\n\n"
        f"## Target users\n\n{_prose_fence('target-users', '_Who uses this?_')}\n\n"
        f"## Architecture\n\n{_prose_fence('architecture', '_Key technical decisions._')}\n\n"
        f"## Why now\n\n{_prose_fence('why', '_Why prioritize this now?_')}\n"
    )

    rel = _safe_write(path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run, "created": True}


# ---------------------------------------------------------------------------
# generate_projects_index
# ---------------------------------------------------------------------------

def generate_projects_index(
    vault: "str | Path",
    *,
    now_iso: str,
    dry_run: bool = False,
) -> dict:
    """Generate ``Projects.md`` — an index of all projects.

    Returns ``{path, dry_run}``.
    """
    from obsidian_connector import creation_projects as cp
    from obsidian_connector import creation_backlog as cb

    vault_path = Path(vault)
    projects = cp.list_projects(vault_path)

    rows: list[list[str]] = []
    for proj in projects:
        backlog = cb.list_backlog(vault_path, project=proj.slug)
        n_open = sum(1 for i in backlog if i.get("status") not in ("done", "archived"))
        repos_str = ", ".join(proj.repos[:5])
        if len(proj.repos) > 5:
            repos_str += f" (+{len(proj.repos) - 5})"
        rows.append([
            f"[[Projects/{proj.name}/Project Dashboard|{proj.name}]]",
            proj.status,
            str(len(proj.repos)),
            str(n_open),
            repos_str,
        ])

    table = _table(["Project", "Status", "Repos", "Open items", "Repos list"], rows)

    fm = _fm({
        "type": "projects-index",
        "last_sync": now_iso,
        "generated_by": "creation_dashboards",
    })

    content = (
        f"{fm}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"# Projects\n\n"
        f"_Last sync: {now_iso} · {len(projects)} projects_\n\n"
        f"{table}\n\n"
        "---\n\n"
        "**Links:** [[Dashboard]] · [[Next Actions]] · [[Stale Context]]\n"
    )

    path = vault_path / "Projects.md"
    rel = _safe_write(path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run}


# ---------------------------------------------------------------------------
# generate_next_actions
# ---------------------------------------------------------------------------

def generate_next_actions(
    vault: "str | Path",
    *,
    now_iso: str,
    github_root: "str | Path | None" = None,
    dry_run: bool = False,
    runner: "Callable | None" = None,
    limit: int = 20,
) -> dict:
    """Generate ``Next Actions.md`` — ranked recommendations with reasoning.

    Each item shows: rank, action, project·repo, confidence, reason chips,
    flags, suggested workflow, context-pack link.  Footer explains the
    transparent scoring formula + that weights are user-editable.

    Returns ``{path, dry_run}``.
    """
    from obsidian_connector import creation_next as cn

    vault_path = Path(vault)
    gh_root = Path(github_root) if github_root else Path.home() / "dev"
    runner_kwargs: dict = {}
    if runner is not None:
        runner_kwargs["runner"] = runner

    recs = cn.next_actions(
        vault_path,
        scope="global",
        github_root=gh_root,
        now_iso=now_iso,
        limit=limit,
        **runner_kwargs,
    )

    lines: list[str] = []
    for rank, rec in enumerate(recs, 1):
        proj = rec.get("project") or ""
        repo = rec.get("repo") or ""
        loc = " · ".join(x for x in [proj, repo] if x)
        reasons = rec.get("reason") or []
        reason_chips = "  ".join(f"`{r}`" for r in reasons[:3])
        confidence = rec.get("confidence", 0.0)
        conf_str = f"{confidence:.0%}"
        action = rec.get("action", "")

        flags: list[str] = []
        if rec.get("requires_mario_decision"):
            flags.append("[needs-decision]")
        # detect blocked from reasons
        if any("blocked" in str(r).lower() for r in reasons):
            flags.append("[blocked]")

        workflow = rec.get("suggested_workflow")
        ctx_pack = rec.get("context_pack")

        item_lines = [f"### {rank}. {action}"]
        if loc:
            item_lines.append(f"**Project · Repo:** {loc}")
        item_lines.append(f"**Confidence:** {conf_str}")
        if reason_chips:
            item_lines.append(f"**Reasons:** {reason_chips}")
        if flags:
            item_lines.append("**Flags:** " + "  ".join(flags))
        if workflow:
            item_lines.append(f"**Suggested workflow:** {workflow}")
        if ctx_pack:
            item_lines.append(f"**Context pack:** {ctx_pack}")
        lines.append("\n".join(item_lines))

    if not lines:
        lines = ["_No recommendations generated._"]

    fm = _fm({
        "type": "next-actions",
        "last_sync": now_iso,
        "generated_by": "creation_dashboards",
    })

    weights_path = "creation/dashboard-weights.json"
    footer = (
        "---\n\n"
        "**Scoring formula:** `score = sum(weight[k] * signal[k])` where signals are "
        "normalized 0-1 per factor (urgency, impact, dependency_unlock, stale_age, "
        "user_emphasis, deadline, unfinished_session, repo_readiness).  "
        f"Weights are user-editable in `{weights_path}` in the vault root.\n\n"
        "**Links:** [[Dashboard]] · [[Projects]] · [[Stale Context]] · [[Pending Decisions]]\n"
    )

    content = (
        f"{fm}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"# Next Actions\n\n"
        f"_Last sync: {now_iso} · {len(recs)} recommendations_\n\n"
        + "\n\n".join(lines)
        + f"\n\n{footer}"
    )

    path = vault_path / "Next Actions.md"
    rel = _safe_write(path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run}


# ---------------------------------------------------------------------------
# generate_stale_context
# ---------------------------------------------------------------------------

def generate_stale_context(
    vault: "str | Path",
    *,
    now_iso: str,
    dry_run: bool = False,
) -> dict:
    """Generate ``Stale Context.md`` from ``freshness_audit``.

    Returns ``{path, dry_run}``.
    """
    from obsidian_connector.creation_status import freshness_audit

    vault_path = Path(vault)
    audit = freshness_audit(vault_path, now_iso=now_iso)

    stale = audit.get("stale", [])
    conflicting = audit.get("conflicting", [])
    checked = audit.get("checked", 0)

    stale_lines: list[str] = []
    for item in stale:
        bid = item.get("id", "?")
        fpath = item.get("path", "?")
        src_repo = item.get("source_repo") or ""
        src_note = f" (repo: `{src_repo}`)" if src_repo else ""
        stale_lines.append(f"- `{bid}` — `{fpath}`{src_note}")
    if not stale_lines:
        stale_lines = ["_No stale items._"]

    conflict_lines: list[str] = []
    for item in conflicting:
        bid = item.get("id", "?")
        fpath = item.get("path", "?")
        conflict_lines.append(f"- `{bid}` — `{fpath}`")
    if not conflict_lines:
        conflict_lines = ["_No conflicting items._"]

    fm = _fm({
        "type": "stale-context",
        "last_sync": now_iso,
        "generated_by": "creation_dashboards",
    })

    content = (
        f"{fm}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"# Stale Context\n\n"
        f"_Last sync: {now_iso} · {checked} items checked_\n\n"
        f"## Stale ({len(stale)})\n\n"
        + "\n".join(stale_lines)
        + f"\n\n## Conflicting ({len(conflicting)})\n\n"
        + "\n".join(conflict_lines)
        + "\n\n---\n\n"
        "**Links:** [[Dashboard]] · [[Pending Decisions]] · [[Next Actions]]\n"
    )

    path = vault_path / "Stale Context.md"
    rel = _safe_write(path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run}


# ---------------------------------------------------------------------------
# generate_pending_decisions
# ---------------------------------------------------------------------------

def generate_pending_decisions(
    vault: "str | Path",
    *,
    now_iso: str,
    dry_run: bool = False,
) -> dict:
    """Generate ``Pending Decisions.md`` — backlog items flagged needs_decision.

    Returns ``{path, dry_run}``.
    """
    from obsidian_connector import creation_backlog as cb

    vault_path = Path(vault)
    all_items = cb.list_backlog(vault_path)
    decision_items = [i for i in all_items if i.get("needs_decision")]

    lines: list[str] = []
    for item in decision_items:
        pri = item.get("priority", "?")
        project = item.get("project", "?")
        title = item.get("title", item["id"])
        bid = item["id"]
        na = item.get("next_action") or "_no next action_"
        lines.append(
            f"- `{pri}` **{title}** (project: `{project}`)  `{bid}`\n"
            f"  Next action: {na}"
        )

    if not lines:
        lines = ["_No pending decisions._"]

    fm = _fm({
        "type": "pending-decisions",
        "last_sync": now_iso,
        "generated_by": "creation_dashboards",
    })

    content = (
        f"{fm}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"# Pending Decisions\n\n"
        f"_Last sync: {now_iso} · {len(decision_items)} items need a decision_\n\n"
        + "\n\n".join(lines)
        + "\n\n---\n\n"
        "**Links:** [[Dashboard]] · [[Next Actions]] · [[Stale Context]]\n"
    )

    path = vault_path / "Pending Decisions.md"
    rel = _safe_write(path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run}


# ---------------------------------------------------------------------------
# generate_active_sessions
# ---------------------------------------------------------------------------

def generate_active_sessions(
    vault: "str | Path",
    *,
    now_iso: str,
    dry_run: bool = False,
) -> dict:
    """Generate ``Active Sessions.md`` — active marker + recent session notes.

    Returns ``{path, dry_run}``.
    """
    from obsidian_connector.creation_session import active_session

    vault_path = Path(vault)
    active = active_session(vault_path)

    # Collect recent session notes (sorted by name descending = newest first)
    sessions_dir = vault_path / "sessions"
    session_files: list[Path] = []
    if sessions_dir.is_dir():
        session_files = sorted(
            [p for p in sessions_dir.iterdir()
             if p.is_file() and p.suffix == ".md" and p.name != "_active.md"],
            reverse=True,
        )[:20]

    active_section: str
    if active:
        active_section = f"**Active session:** `{active}`\n\n[[sessions/{active}]]"
    else:
        active_section = "_No active session._"

    session_lines: list[str] = []
    for sf in session_files:
        session_lines.append(f"- [[sessions/{sf.stem}]]")
    if not session_lines:
        session_lines = ["_No session notes found._"]

    fm = _fm({
        "type": "active-sessions",
        "last_sync": now_iso,
        "generated_by": "creation_dashboards",
    })

    content = (
        f"{fm}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"# Active Sessions\n\n"
        f"_Last sync: {now_iso}_\n\n"
        f"## Active\n\n{active_section}\n\n"
        f"## Recent sessions ({len(session_files)})\n\n"
        + "\n".join(session_lines)
        + "\n\n---\n\n"
        "**Links:** [[Dashboard]] · [[Next Actions]]\n"
    )

    path = vault_path / "Active Sessions.md"
    rel = _safe_write(path, content, vault_path, dry_run)
    return {"path": rel, "dry_run": dry_run}


# ---------------------------------------------------------------------------
# refresh_all — orchestrator
# ---------------------------------------------------------------------------

def refresh_all(
    vault: "str | Path",
    *,
    now_iso: str,
    github_root: "str | Path | None" = None,
    scope: "str | None" = None,
    dry_run: bool = False,
    runner: "Callable | None" = None,
) -> dict:
    """Regenerate the full global dashboard set.

    When *scope* names a project slug, also regenerates that project's
    drilldown dashboards (project dashboard + one-pager scaffold + repo views).
    When *scope* names a repo dir_name, regenerates the global set plus the
    containing project's and that repo's view.

    Parameters
    ----------
    vault:
        Vault root path.
    now_iso:
        ISO8601 timestamp (clock boundary: supplied by the caller).
    github_root:
        Root of local git repos (default: ``~/dev``).
    scope:
        Optional project slug or repo dir_name to additionally drill into.
    dry_run:
        When True, skip all writes and return the list of paths that
        *would* have been written.
    runner:
        Injectable subprocess runner for tests.

    Returns
    -------
    dict
        ``{written: list[str], dry_run: bool}``
    """
    from obsidian_connector import creation_projects as cp

    vault_path = Path(vault)
    gh_root = Path(github_root) if github_root else Path.home() / "dev"

    written: list[str] = []
    kw: dict = dict(now_iso=now_iso, github_root=gh_root, dry_run=dry_run, runner=runner)

    # Global set (always)
    for fn in [
        lambda: generate_global_dashboard(vault_path, **kw),
        lambda: generate_projects_index(vault_path, now_iso=now_iso, dry_run=dry_run),
        lambda: generate_next_actions(vault_path, **kw),
        lambda: generate_stale_context(vault_path, now_iso=now_iso, dry_run=dry_run),
        lambda: generate_pending_decisions(vault_path, now_iso=now_iso, dry_run=dry_run),
        lambda: generate_active_sessions(vault_path, now_iso=now_iso, dry_run=dry_run),
    ]:
        try:
            result = fn()
            if result.get("path"):
                written.append(result["path"])
        except Exception:
            pass

    if scope is None:
        return {"written": written, "dry_run": dry_run}

    # Resolve scope to a project (and optionally a repo)
    projects = cp.list_projects(vault_path)
    scoped_project: "cp.Project | None" = None
    scoped_repo: str | None = None

    # Check if scope is a project slug/name
    scoped_project = cp.get_project(vault_path, scope)
    if scoped_project is None:
        # Check if scope is a repo dir_name belonging to any project
        for proj in projects:
            if scope in proj.repos:
                scoped_project = proj
                scoped_repo = scope
                break

    if scoped_project is not None:
        # Project drilldowns
        try:
            r = generate_project_dashboard(vault_path, scoped_project.slug, **kw)
            if r.get("path"):
                written.append(r["path"])
        except Exception:
            pass
        try:
            r = generate_project_one_pager(vault_path, scoped_project.slug,
                                           now_iso=now_iso, dry_run=dry_run)
            if r.get("path"):
                written.append(r["path"])
        except Exception:
            pass

        # Repo views: if scoped to a repo, only that one; else all project repos
        repos_to_refresh = [scoped_repo] if scoped_repo else list(scoped_project.repos)
        for repo_name in repos_to_refresh:
            try:
                r = generate_repo_view(vault_path, scoped_project.slug, repo_name, **kw)
                if r.get("path"):
                    written.append(r["path"])
            except Exception:
                pass

    return {"written": written, "dry_run": dry_run}
